apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"release":"prometheus"},"name":"demo-app-alerts","namespace":"demo-loadtest"},"spec":{"groups":[{"name":"demo-app","rules":[{"alert":"KubePodSchedulingFailed","annotations":{"description":"Workload pods in namespace {{ $labels.namespace }} have not been scheduled. Service capacity may be degraded.\n","summary":"One or more pods in namespace {{ $labels.namespace }} are stuck in Pending state.\n"},"expr":"kube_pod_status_phase{namespace=\"demo-loadtest\", phase=\"Pending\"} \u003e 0\n","for":"30s","labels":{"severity":"critical"}}]}]}}
      prometheus-operator-validated: "true"
    creationTimestamp: "2026-10-03T03:18:47Z"
    generation: 2
    labels:
      release: prometheus
    name: demo-app-alerts
    namespace: demo-loadtest
    resourceVersion: "60774"
    uid: 4d0aa44f-0c86-4a3c-8923-4ad22b4941d0
  spec:
    groups:
    - name: demo-app
      rules:
      - alert: KubePodSchedulingFailed
        annotations:
          description: |
            Workload pods in namespace {{ $labels.namespace }} have not been scheduled. Service capacity may be degraded.
          summary: |
            One or more pods in namespace {{ $labels.namespace }} are stuck in Pending state.
        expr: |
          kube_pod_status_phase{namespace="demo-loadtest", phase="Pending"} > 0
        for: 30s
        labels:
          cluster: remote-cluster
          severity: critical
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kubernaut-demo-scenarios","release":"kube-prometheus-stack"},"name":"demo-app-metrics","namespace":"demo-loadtest"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"http"}],"selector":{"matchLabels":{"kubernaut.ai/metrics":"true"}}}}
    creationTimestamp: "2026-10-03T03:18:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: kubernaut-demo-scenarios
      release: kube-prometheus-stack
    name: demo-app-metrics
    namespace: demo-loadtest
    resourceVersion: "60784"
    uid: a70508d5-df8d-48fe-a37d-f67e92d7ea02
  spec:
    endpoints:
    - interval: 10s
      path: /metrics
      port: http
    selector:
      matchLabels:
        kubernaut.ai/metrics: "true"
kind: List
metadata:
  resourceVersion: ""
