apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2026-10-02T18:54:14-04:00"
    creationTimestamp: "2026-10-02T22:54:14Z"
    generateName: worker-5bdbf847dd-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 5bdbf847dd
    name: worker-5bdbf847dd-qqps9
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-5bdbf847dd
      uid: 3c21536d-b2dd-4938-b33a-761a563b1c79
    resourceVersion: "26904"
    uid: 05c8547e-ff49-4375-b856-7c3f757ec7aa
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-h9d6b
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-h9d6b
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:54:15Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:54:15Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:54:15Z"
      message: 'containers with unready status: [worker]'
      observedGeneration: 1
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:54:15Z"
      message: 'containers with unready status: [worker]'
      observedGeneration: 1
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:54:15Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://92edeb14f0af1e8e9bed3af3c72f7a1dc6ca9641263e519325c2aca0dd8b4d52
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState:
        terminated:
          containerID: containerd://92edeb14f0af1e8e9bed3af3c72f7a1dc6ca9641263e519325c2aca0dd8b4d52
          exitCode: 1
          finishedAt: "2026-10-02T23:00:08Z"
          reason: Error
          startedAt: "2026-10-02T23:00:08Z"
      name: worker
      ready: false
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 6
      started: false
      state:
        waiting:
          message: back-off 5m0s restarting failed container=worker pod=worker-5bdbf847dd-qqps9_demo-workers(05c8547e-ff49-4375-b856-7c3f757ec7aa)
          reason: CrashLoopBackOff
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-h9d6b
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.67
    podIPs:
    - ip: 10.244.0.67
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T22:54:15Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-02T22:53:49Z"
    generateName: worker-68f8898c86-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 68f8898c86
    name: worker-68f8898c86-ndgqv
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-68f8898c86
      uid: 3581414b-1b6e-4e82-8d02-3e0893be647e
    resourceVersion: "26004"
    uid: 84337f2a-b490-46a5-9104-12d610e599df
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-m277h
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-m277h
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:50Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:49Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:54Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:54Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:49Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://cd102b3a24dd87d2a5d58b72b84baa5cf444e61d1ad18ffd0d07976c93a30539
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: worker
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-02T22:53:51Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-m277h
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.66
    podIPs:
    - ip: 10.244.0.66
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T22:53:49Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-02T22:53:49Z"
    generateName: worker-68f8898c86-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 68f8898c86
    name: worker-68f8898c86-r78mq
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-68f8898c86
      uid: 3581414b-1b6e-4e82-8d02-3e0893be647e
    resourceVersion: "26010"
    uid: 010cd0ce-382f-4301-bb94-f3a9536e6b91
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-624v6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-624v6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:50Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:49Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:54Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:54Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T22:53:49Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://798cf444fc3ba0d5b7264768e0a0d66a338cefd0ae3cd080aa96f2b51b3b9161
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: worker
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-02T22:53:51Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-624v6
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.65
    podIPs:
    - ip: 10.244.0.65
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T22:53:49Z"
kind: List
metadata:
  resourceVersion: ""
