apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: demo-operator
spec:
  channel: singlenamespace-alpha
  name: etcd
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
