apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - networkpolicy-allow.yaml
  - prometheus-rule.yaml
components:
  - ../../components/metrics-servicemonitor
