apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-warehouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea:3000/kubernaut/demo-warehouse-repo.git
    targetRevision: main
    path: disk-pressure-emptydir
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-warehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
