apiVersion: v1
items:
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:34Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: wfe-c301d0988b7a53cf-s5855
    namespace: kubernaut-workflows
    resourceVersion: "40410"
    uid: 93cf70a4-c9f6-4a67-a1d5-386f6123dc38
  kind: Event
  lastTimestamp: "2026-10-03T00:43:34Z"
  message: Successfully assigned kubernaut-workflows/wfe-c301d0988b7a53cf-s5855 to
    kubernaut-remote-cluster-control-plane
  metadata:
    creationTimestamp: "2026-10-03T00:43:34Z"
    name: wfe-c301d0988b7a53cf-s5855.18dade4abff9036c
    namespace: kubernaut-workflows
    resourceVersion: "40414"
    uid: 9cec22e0-193e-49d0-a018-05f6c7b7968d
  reason: Scheduled
  reportingComponent: default-scheduler
  reportingInstance: ""
  source:
    component: default-scheduler
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:34Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{workflow}
    kind: Pod
    name: wfe-c301d0988b7a53cf-s5855
    namespace: kubernaut-workflows
    resourceVersion: "40413"
    uid: 93cf70a4-c9f6-4a67-a1d5-386f6123dc38
  kind: Event
  lastTimestamp: "2026-10-03T00:43:34Z"
  message: Pulling image "quay.io/kubernaut-cicd/test-workflows/helm-rollback-job@sha256:d7739e5bcf1270e32ec36ed7a6a528fe99e4d12a3fa2d55d9eaaddee2a107d25"
  metadata:
    creationTimestamp: "2026-10-03T00:43:34Z"
    name: wfe-c301d0988b7a53cf-s5855.18dade4adb43b9fb
    namespace: kubernaut-workflows
    resourceVersion: "40417"
    uid: 441183e0-fd1d-4b36-b98f-1125ee8b44d2
  reason: Pulling
  reportingComponent: kubelet
  reportingInstance: kubernaut-remote-cluster-control-plane
  source:
    component: kubelet
    host: kubernaut-remote-cluster-control-plane
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:42Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{workflow}
    kind: Pod
    name: wfe-c301d0988b7a53cf-s5855
    namespace: kubernaut-workflows
    resourceVersion: "40413"
    uid: 93cf70a4-c9f6-4a67-a1d5-386f6123dc38
  kind: Event
  lastTimestamp: "2026-10-03T00:43:42Z"
  message: 'Successfully pulled image "quay.io/kubernaut-cicd/test-workflows/helm-rollback-job@sha256:d7739e5bcf1270e32ec36ed7a6a528fe99e4d12a3fa2d55d9eaaddee2a107d25"
    in 7.999s (7.999s including waiting). Image size: 75309548 bytes.'
  metadata:
    creationTimestamp: "2026-10-03T00:43:42Z"
    name: wfe-c301d0988b7a53cf-s5855.18dade4cb80fc083
    namespace: kubernaut-workflows
    resourceVersion: "40434"
    uid: e5c160de-e871-4b85-977a-23f78d882e93
  reason: Pulled
  reportingComponent: kubelet
  reportingInstance: kubernaut-remote-cluster-control-plane
  source:
    component: kubelet
    host: kubernaut-remote-cluster-control-plane
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:42Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{workflow}
    kind: Pod
    name: wfe-c301d0988b7a53cf-s5855
    namespace: kubernaut-workflows
    resourceVersion: "40413"
    uid: 93cf70a4-c9f6-4a67-a1d5-386f6123dc38
  kind: Event
  lastTimestamp: "2026-10-03T00:43:42Z"
  message: Container created
  metadata:
    creationTimestamp: "2026-10-03T00:43:42Z"
    name: wfe-c301d0988b7a53cf-s5855.18dade4cb99712f0
    namespace: kubernaut-workflows
    resourceVersion: "40435"
    uid: f589259c-19cc-40be-8952-40009b7347e2
  reason: Created
  reportingComponent: kubelet
  reportingInstance: kubernaut-remote-cluster-control-plane
  source:
    component: kubelet
    host: kubernaut-remote-cluster-control-plane
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:43Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{workflow}
    kind: Pod
    name: wfe-c301d0988b7a53cf-s5855
    namespace: kubernaut-workflows
    resourceVersion: "40413"
    uid: 93cf70a4-c9f6-4a67-a1d5-386f6123dc38
  kind: Event
  lastTimestamp: "2026-10-03T00:43:43Z"
  message: Container started
  metadata:
    creationTimestamp: "2026-10-03T00:43:43Z"
    name: wfe-c301d0988b7a53cf-s5855.18dade4cc583257b
    namespace: kubernaut-workflows
    resourceVersion: "40437"
    uid: 1955f1e8-1470-4437-b7ed-44c579bebdb2
  reason: Started
  reportingComponent: kubelet
  reportingInstance: kubernaut-remote-cluster-control-plane
  source:
    component: kubelet
    host: kubernaut-remote-cluster-control-plane
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:34Z"
  involvedObject:
    apiVersion: batch/v1
    kind: Job
    name: wfe-c301d0988b7a53cf
    namespace: kubernaut-workflows
    resourceVersion: "40409"
    uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
  kind: Event
  lastTimestamp: "2026-10-03T00:43:34Z"
  message: 'Created pod: wfe-c301d0988b7a53cf-s5855'
  metadata:
    creationTimestamp: "2026-10-03T00:43:34Z"
    name: wfe-c301d0988b7a53cf.18dade4abea227d8
    namespace: kubernaut-workflows
    resourceVersion: "40412"
    uid: 892754d8-1fc4-4cdc-a84b-d7cdbd27c758
  reason: SuccessfulCreate
  reportingComponent: job-controller
  reportingInstance: ""
  source:
    component: job-controller
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-10-03T00:43:46Z"
  involvedObject:
    apiVersion: batch/v1
    kind: Job
    name: wfe-c301d0988b7a53cf
    namespace: kubernaut-workflows
    resourceVersion: "40456"
    uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
  kind: Event
  lastTimestamp: "2026-10-03T00:43:46Z"
  message: Job has reached the specified backoff limit
  metadata:
    creationTimestamp: "2026-10-03T00:43:46Z"
    name: wfe-c301d0988b7a53cf.18dade4d7b57a584
    namespace: kubernaut-workflows
    resourceVersion: "40459"
    uid: 09006e67-6d4d-46d4-93e0-ecaae069f873
  reason: BackoffLimitExceeded
  reportingComponent: job-controller
  reportingInstance: ""
  source:
    component: job-controller
  type: Warning
kind: List
metadata:
  resourceVersion: ""
