apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubernaut.ai/target-resource: demo-backend/Deployment/worker
  creationTimestamp: "2026-10-03T00:43:34Z"
  generation: 1
  labels:
    kubernaut.ai/execution-engine: job
    kubernaut.ai/source-namespace: kubernaut-system
    kubernaut.ai/target-resource: demo-backend__Deployment__worker
    kubernaut.ai/workflow-execution: we-rr-1c290d778763-4c59d6de
    kubernaut.ai/workflow-id: 0aa9e14b-13ab-5b61-af2f-c78ccf4e8d24
  name: wfe-c301d0988b7a53cf
  namespace: kubernaut-workflows
  resourceVersion: "40458"
  uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
spec:
  activeDeadlineSeconds: 1799
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - status: "True"
        type: DisruptionTarget
    - action: Ignore
      onExitCodes:
        containerName: workflow
        operator: In
        values:
        - 137
  podReplacementPolicy: Failed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/controller-uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
        batch.kubernetes.io/job-name: wfe-c301d0988b7a53cf
        controller-uid: e27d481d-acdc-44c2-9f98-9f201db3ec09
        job-name: wfe-c301d0988b7a53cf
        kubernaut.ai/execution-engine: job
        kubernaut.ai/workflow-execution: we-rr-1c290d778763-4c59d6de
    spec:
      containers:
      - env:
        - name: TARGET_RESOURCE
          value: demo-backend/Deployment/worker
        - name: TARGET_RESOURCE_NAMESPACE
          value: demo-backend
        - name: TARGET_RESOURCE_KIND
          value: Deployment
        - name: TARGET_RESOURCE_NAME
          value: worker
        - name: HOME
          value: /tmp
        - name: TMPDIR
          value: /tmp
        image: quay.io/kubernaut-cicd/test-workflows/helm-rollback-job@sha256:d7739e5bcf1270e32ec36ed7a6a528fe99e4d12a3fa2d55d9eaaddee2a107d25
        imagePullPolicy: IfNotPresent
        name: workflow
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: helm-rollback-v1-runner
      serviceAccountName: helm-rollback-v1-runner
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  conditions:
  - lastProbeTime: "2026-10-03T00:43:46Z"
    lastTransitionTime: "2026-10-03T00:43:46Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: FailureTarget
  - lastProbeTime: "2026-10-03T00:43:46Z"
    lastTransitionTime: "2026-10-03T00:43:46Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  ready: 0
  startTime: "2026-10-03T00:43:34Z"
  terminating: 0
  uncountedTerminatedPods: {}
