apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"release":"prometheus"},"name":"demo-app-alerts","namespace":"demo-compute"},"spec":{"groups":[{"name":"demo-app","rules":[{"alert":"KubeNodeNotReady","annotations":{"description":"A cluster node has transitioned to NotReady status. Workloads scheduled on this node may experience disruption or reduced availability.\n","summary":"Node {{ $labels.node }} is in NotReady state.\n"},"expr":"max by (node) (\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"} == 0\n)\n","for":"30s","labels":{"namespace":"demo-compute","severity":"critical"}}]}]}}
      prometheus-operator-validated: "true"
    creationTimestamp: "2026-10-03T03:45:33Z"
    generation: 2
    labels:
      release: prometheus
    name: demo-app-alerts
    namespace: demo-compute
    resourceVersion: "64826"
    uid: 2ca3e47d-2fad-48b2-98d4-86c33ef848a3
  spec:
    groups:
    - name: demo-app
      rules:
      - alert: KubeNodeNotReady
        annotations:
          description: |
            A cluster node has transitioned to NotReady status. Workloads scheduled on this node may experience disruption or reduced availability.
          summary: |
            Node {{ $labels.node }} is in NotReady state.
        expr: |
          max by (node) (
            kube_node_status_condition{condition="Ready", status="true"} == 0
          )
        for: 30s
        labels:
          cluster: remote-cluster
          namespace: demo-compute
          severity: critical
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kubernaut-demo-scenarios","release":"kube-prometheus-stack"},"name":"demo-app-metrics","namespace":"demo-compute"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"http"}],"selector":{"matchLabels":{"kubernaut.ai/metrics":"true"}}}}
    creationTimestamp: "2026-10-03T03:45:34Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: kubernaut-demo-scenarios
      release: kube-prometheus-stack
    name: demo-app-metrics
    namespace: demo-compute
    resourceVersion: "64828"
    uid: 407b6e6b-385c-4917-b150-2f94553627af
  spec:
    endpoints:
    - interval: 10s
      path: /metrics
      port: http
    selector:
      matchLabels:
        kubernaut.ai/metrics: "true"
kind: List
metadata:
  resourceVersion: ""
