#!/usr/bin/env bash
SCENARIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_NAME="network-policy-block"
DEMO_NS="demo-netpol"
ALERT_NAME="KubePodCrashLooping"
ALERT_QUERY_NS="demo-netpol"
RESOURCE_TAPE="network-policy-block-pods.tape"
SCREENS_TAPE="network-policy-block-screens.tape"
APPROVAL_REQUIRED="false"
TERMINAL_STATE="Completed"
INJECT_CMD="bash ${SCENARIO_DIR}/inject-deny-all-netpol.sh"
SETUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh 2>/dev/null || true && kubectl apply -f ${SCENARIO_DIR}/manifests/ && kubectl wait --for=condition=Available deployment/web-frontend -n demo-netpol --timeout=120s && kubectl wait --for=condition=Available deployment/traffic-gen -n demo-netpol --timeout=120s"
CLEANUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh"
source "$(cd "${SCENARIO_DIR}/../.." && pwd)/scripts/record-scenario.sh"
