apiVersion: kubernaut.ai/v1alpha1
kind: EffectivenessAssessment
metadata:
  creationTimestamp: "2026-10-03T00:56:02Z"
  generation: 1
  name: ea-rr-1c290d778763-37bd1bac
  namespace: kubernaut-system
  ownerReferences:
  - apiVersion: kubernaut.ai/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: RemediationRequest
    name: rr-1c290d778763-37bd1bac
    uid: 7a6e707b-44ab-4c66-8047-f6ffe79fdea1
  resourceVersion: "53190"
  uid: 0e3319a8-c6f0-4bbd-b82c-132e3668af8f
spec:
  clusterID: remote-cluster
  config:
    stabilizationWindow: 5m0s
  correlationID: rr-1c290d778763-37bd1bac
  preRemediationSpecHash: sha256:11dde3aac2d48044f1f6645d591e73eaa8004ed6ca858c25400222f97fa9be13
  remediationCreatedAt: "2026-10-03T00:54:38Z"
  remediationRequestPhase: Verifying
  remediationTarget:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
    namespace: demo-backend
  signalName: KubePodCrashLooping
  signalTarget:
    kind: Deployment
    name: worker
    namespace: demo-backend
status:
  alertManagerCheckAfter: "2026-10-03T01:01:02Z"
  assessmentReason: Full
  completedAt: "2026-10-03T01:01:02Z"
  components:
    alertAssessed: true
    alertScore: 1
    currentSpecHash: sha256:6e0e7cc93927c96c64f5122996ac3c72417e0c460a19b4116462f86fe0b14e06
    hashComputed: true
    healthAssessed: true
    healthScore: 1
    metricsAssessed: true
    metricsScore: 0.25000000000000006
    postRemediationSpecHash: sha256:6e0e7cc93927c96c64f5122996ac3c72417e0c460a19b4116462f86fe0b14e06
  conditions:
  - lastTransitionTime: "2026-10-03T01:01:02Z"
    message: Post-remediation spec hash captured
    observedGeneration: 1
    reason: PostHashCaptured
    status: "True"
    type: PostHashCaptured
  - lastTransitionTime: "2026-10-03T01:01:02Z"
    message: Post-remediation spec hash computed; baseline established
    observedGeneration: 1
    reason: SpecUnchanged
    status: "True"
    type: SpecIntegrity
  - lastTransitionTime: "2026-10-03T01:01:02Z"
    message: Assessment completed
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-03T01:01:02Z"
    message: 'Assessment completed: Full'
    observedGeneration: 1
    reason: AssessmentFull
    status: "True"
    type: AssessmentComplete
  message: 'Assessment completed: Full'
  phase: Completed
  prometheusCheckAfter: "2026-10-03T01:01:02Z"
  validityDeadline: "2026-10-03T01:03:02Z"
