#!/usr/bin/env bash
SCENARIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_NAME="mesh-routing-failure"
DEMO_NS="demo-mesh-failure"
ALERT_NAME="LinkerdHighErrorRate"
RESOURCE_TAPE="mesh-routing-failure-pods.tape"
SCREENS_TAPE="mesh-routing-failure-screens.tape"
APPROVAL_REQUIRED="false"
TERMINAL_STATE="Completed"
INJECT_CMD="bash ${SCENARIO_DIR}/inject-deny-policy.sh"
SETUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh 2>/dev/null || true && kubectl apply -f ${SCENARIO_DIR}/manifests/ && kubectl wait --for=condition=Available deployment/web-api -n demo-mesh-failure --timeout=120s"
CLEANUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh"
SCENARIO_TITLE="Mesh Routing Failure Remediation"
source "$(cd "${SCENARIO_DIR}/../.." && pwd)/scripts/record-scenario.sh"
