apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2026-10-02T01:13:15-04:00"
    creationTimestamp: "2026-10-02T05:13:15Z"
    generateName: kube-mcp-server-697f9bfcbb-
    generation: 1
    labels:
      app: kube-mcp-server
      component: fleet
      pod-template-hash: 697f9bfcbb
    name: kube-mcp-server-697f9bfcbb-68rn6
    namespace: mcp-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: kube-mcp-server-697f9bfcbb
      uid: b116e372-3de2-4741-9216-3f8c39a35c72
    resourceVersion: "98408"
    uid: f2ead9bf-1293-4549-a9b0-f053d2350220
  spec:
    containers:
    - args:
      - --port=8080
      - --cluster-provider=in-cluster
      - --toolsets=core
      - --stateless
      - --list-output=yaml
      - --config=/etc/kubernetes-mcp-server/config.toml
      - --log-level=6
      image: ghcr.io/containers/kubernetes-mcp-server@sha256:4219880ffae9b61f5cf8e27c0536d4001336016a6af77dc5a63dfaf9ce938b97
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: kube-mcp-server
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 250m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/kubernetes-mcp-server
        name: config
        readOnly: true
      - mountPath: /etc/tls-ca
        name: tls-ca
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xprcn
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-hub-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: kube-mcp-server
    serviceAccountName: kube-mcp-server
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: kube-mcp-server-config
      name: config
    - configMap:
        defaultMode: 420
        name: inter-service-ca
      name: tls-ca
    - name: kube-api-access-xprcn
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 50m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T05:33:23Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T05:13:15Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T05:34:24Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T05:34:24Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T05:13:15Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 50m
        memory: 32Mi
      containerID: containerd://230695f17b1bf2118e23ed97c09a319ac6485985fc50e0ed0fad21edef6da415
      image: sha256:ec93b688098b17c3285a66906b02f368a9b1ed575c09ba16d2b635a41abb9fa3
      imageID: ghcr.io/containers/kubernetes-mcp-server@sha256:4219880ffae9b61f5cf8e27c0536d4001336016a6af77dc5a63dfaf9ce938b97
      lastState:
        terminated:
          containerID: containerd://09b473c7fb16f571fa057a941f65d8718efb275b4f08c6ae3d6fd02ee7dd0ace
          exitCode: 1
          finishedAt: "2026-10-02T05:33:55Z"
          reason: Error
          startedAt: "2026-10-02T05:33:45Z"
      name: kube-mcp-server
      ready: true
      resources:
        limits:
          cpu: 250m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 32Mi
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2026-10-02T05:34:18Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 65532
      volumeMounts:
      - mountPath: /etc/kubernetes-mcp-server
        name: config
        readOnly: true
        recursiveReadOnly: Disabled
      - mountPath: /etc/tls-ca
        name: tls-ca
        readOnly: true
        recursiveReadOnly: Disabled
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xprcn
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.2
    hostIPs:
    - ip: 10.89.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.31
    podIPs:
    - ip: 10.244.0.31
    qosClass: Burstable
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 28m
        memory: 32Mi
    startTime: "2026-10-02T05:13:15Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"component":"identity","kubernaut.ai/managed":"true"},"name":"keycloak","namespace":"mcp-system"},"spec":{"externalName":"keycloak.idp.svc.cluster.local","type":"ExternalName"}}
    creationTimestamp: "2026-10-01T19:32:52Z"
    labels:
      component: identity
      kubernaut.ai/managed: "true"
    name: keycloak
    namespace: mcp-system
    resourceVersion: "1421"
    uid: 1ab281a4-4362-42d3-a9bd-2e9c5b369e81
  spec:
    externalName: keycloak.idp.svc.cluster.local
    sessionAffinity: None
    type: ExternalName
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kube-mcp-server","component":"fleet"},"name":"kube-mcp-server","namespace":"mcp-system"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"kube-mcp-server"}}}
    creationTimestamp: "2026-10-01T19:33:59Z"
    labels:
      app: kube-mcp-server
      component: fleet
    name: kube-mcp-server
    namespace: mcp-system
    resourceVersion: "1891"
    uid: edde4934-7c73-4787-8689-7555b4f6eea4
  spec:
    clusterIP: 10.96.226.196
    clusterIPs:
    - 10.96.226.196
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: kube-mcp-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kube-mcp-server-remote","namespace":"mcp-system"},"spec":{"ports":[{"port":8080,"targetPort":30180}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    name: kube-mcp-server-remote
    namespace: mcp-system
    resourceVersion: "1966"
    uid: 14204281-4f1a-4f56-823d-f613d4c724e4
  spec:
    clusterIP: 10.96.51.133
    clusterIPs:
    - 10.96.51.133
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 30180
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-10-02T05:34:24Z"
    creationTimestamp: "2026-10-01T19:33:59Z"
    labels:
      app: kube-mcp-server
      component: fleet
      endpoints.kubernetes.io/managed-by: endpoint-controller
    name: kube-mcp-server
    namespace: mcp-system
    resourceVersion: "98409"
    uid: 256dc3fe-c328-452f-b3e2-d48f0cfd3b20
  subsets:
  - addresses:
    - ip: 10.244.0.31
      nodeName: kubernaut-hub-control-plane
      targetRef:
        kind: Pod
        name: kube-mcp-server-697f9bfcbb-68rn6
        namespace: mcp-system
        uid: f2ead9bf-1293-4549-a9b0-f053d2350220
    ports:
    - name: http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Endpoints","metadata":{"annotations":{},"name":"kube-mcp-server-remote","namespace":"mcp-system"},"subsets":[{"addresses":[{"ip":"10.89.0.5"}],"ports":[{"port":30180}]}]}
    creationTimestamp: "2026-10-01T19:34:16Z"
    name: kube-mcp-server-remote
    namespace: mcp-system
    resourceVersion: "95558"
    uid: f4ef2af1-2b81-4d8a-8af6-cd2f1c0947fa
  subsets:
  - addresses:
    - ip: 10.89.0.3
    ports:
    - port: 30180
      protocol: TCP
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"Backend","metadata":{"annotations":{},"labels":{"environment":"hub","kubernaut.ai/managed":"true"},"name":"hub","namespace":"mcp-system"},"spec":{"endpoints":[{"fqdn":{"hostname":"kube-mcp-server.mcp-system.svc.cluster.local","port":8080}}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    generation: 1
    labels:
      environment: hub
      kubernaut.ai/managed: "true"
    name: hub
    namespace: mcp-system
    resourceVersion: "2001"
    uid: 7d6102a2-af53-4aae-9fd3-47f44df53af8
  spec:
    endpoints:
    - fqdn:
        hostname: kube-mcp-server.mcp-system.svc.cluster.local
        port: 8080
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"Backend","metadata":{"annotations":{},"name":"keycloak-jwks","namespace":"mcp-system"},"spec":{"endpoints":[{"fqdn":{"hostname":"keycloak.idp.svc.cluster.local","port":8443}}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    generation: 1
    name: keycloak-jwks
    namespace: mcp-system
    resourceVersion: "2009"
    uid: f039131c-a30a-443e-93f9-c7e7f63b5ceb
  spec:
    endpoints:
    - fqdn:
        hostname: keycloak.idp.svc.cluster.local
        port: 8443
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    creationTimestamp: "2026-10-01T19:34:17Z"
    generation: 1
    name: mcp-system-kube-mcp-server-route-mcp-proxy
    namespace: mcp-system
    ownerReferences:
    - apiVersion: aigateway.envoyproxy.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: MCPRoute
      name: kube-mcp-server-route
      uid: d859ad54-0ecb-4d58-b907-025f645e4bcd
    resourceVersion: "1986"
    uid: a44ae9f0-10f9-48d4-b932-6e6d4c6866b5
  spec:
    endpoints:
    - ip:
        address: 192.0.2.42
        port: 9856
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"Backend","metadata":{"annotations":{},"labels":{"kubernaut.ai/managed":"true"},"name":"prod-east","namespace":"mcp-system"},"spec":{"endpoints":[{"fqdn":{"hostname":"kube-mcp-server-remote.mcp-system.svc.cluster.local","port":8080}}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    generation: 1
    labels:
      kubernaut.ai/managed: "true"
    name: prod-east
    namespace: mcp-system
    resourceVersion: "1993"
    uid: 18bf2c4e-fa61-4f57-bfb6-b7cc3ec898b0
  spec:
    endpoints:
    - fqdn:
        hostname: kube-mcp-server-remote.mcp-system.svc.cluster.local
        port: 8080
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"Backend","metadata":{"annotations":{},"labels":{"kubernaut.ai/managed":"true"},"name":"prod-west","namespace":"mcp-system"},"spec":{"endpoints":[{"fqdn":{"hostname":"kube-mcp-server-remote.mcp-system.svc.cluster.local","port":8080}}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    generation: 1
    labels:
      kubernaut.ai/managed: "true"
    name: prod-west
    namespace: mcp-system
    resourceVersion: "1998"
    uid: 3b169e8a-18d7-42b7-9707-3acd36f04984
  spec:
    endpoints:
    - fqdn:
        hostname: kube-mcp-server-remote.mcp-system.svc.cluster.local
        port: 8080
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"Backend","metadata":{"annotations":{},"labels":{"environment":"production","kubernaut.ai/managed":"true"},"name":"remote-cluster","namespace":"mcp-system"},"spec":{"endpoints":[{"fqdn":{"hostname":"kube-mcp-server-remote.mcp-system.svc.cluster.local","port":8080}}]}}
    creationTimestamp: "2026-10-01T19:34:16Z"
    generation: 1
    labels:
      environment: production
      kubernaut.ai/managed: "true"
    name: remote-cluster
    namespace: mcp-system
    resourceVersion: "1989"
    uid: b4ec7d43-35e4-4086-9019-1cf43597798f
  spec:
    endpoints:
    - fqdn:
        hostname: kube-mcp-server-remote.mcp-system.svc.cluster.local
        port: 8080
    type: Endpoints
  status:
    conditions:
    - lastTransitionTime: "2026-10-01T19:34:17Z"
      message: The Backend was accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
kind: List
metadata:
  resourceVersion: ""
