apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-memory-gitops-ansible
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea:3000/kubernaut/demo-memory-gitops-repo.git
    targetRevision: main
    path: memory-gitops-ansible
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-memory-gitops-ansible
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
