apiVersion: v1
kind: ConfigMap
metadata:
  name: build-source-config
  namespace: demo-build
  labels:
    app: webapp
    kubernaut.ai/purpose: known-good-source
data:
  git-uri: "https://github.com/sclorg/httpd-ex.git"
  git-ref: "master"
