#!/usr/bin/env bash
SCENARIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_NAME="duplicate-alert-suppression"
DEMO_NS="demo-ingress"
ALERT_NAME="KubePodCrashLooping"
ALERT_QUERY_NS="demo-ingress"
RESOURCE_TAPE="duplicate-alert-suppression-pods.tape"
SCREENS_TAPE="duplicate-alert-suppression-screens.tape"
APPROVAL_REQUIRED="false"
TERMINAL_STATE="Completed"
INJECT_CMD="bash ${SCENARIO_DIR}/inject-bad-config.sh"
SETUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh 2>/dev/null || true && kubectl apply -f ${SCENARIO_DIR}/manifests/ && kubectl wait --for=condition=Available deployment/web-cluster -n demo-ingress --timeout=120s"
CLEANUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh"
source "$(cd "${SCENARIO_DIR}/../.." && pwd)/scripts/record-scenario.sh"
