apiVersion: kubernaut.ai/v1alpha1
kind: EffectivenessAssessment
metadata:
  creationTimestamp: "2026-10-03T15:17:16Z"
  generation: 1
  name: ea-rr-825b58c1ca42-c9f71ce7
  namespace: kubernaut-system
  ownerReferences:
  - apiVersion: kubernaut.ai/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: RemediationRequest
    name: rr-825b58c1ca42-c9f71ce7
    uid: 60097afd-0c5b-4fca-b440-deb7de6490f0
  resourceVersion: "170829"
  uid: d4ed6a8c-56ac-4380-866a-583dbae89b0e
spec:
  clusterID: remote-cluster
  config:
    stabilizationWindow: 5m0s
  correlationID: rr-825b58c1ca42-c9f71ce7
  preRemediationSpecHash: sha256:885947ff9100a0e9292c6db1790245027c859d6cb76ecc51ccc343788f218880
  remediationCreatedAt: "2026-10-03T15:14:03Z"
  remediationRequestPhase: Verifying
  remediationTarget:
    apiVersion: apps/v1
    kind: Deployment
    name: batch-processor
    namespace: demo-scheduler
  signalName: KubePodNotScheduled
  signalTarget:
    kind: Deployment
    name: batch-processor
    namespace: demo-scheduler
status:
  alertManagerCheckAfter: "2026-10-03T15:22:16Z"
  assessmentReason: MetricsTimedOut
  completedAt: "2026-10-03T15:24:16Z"
  components:
    alertAssessed: true
    alertScore: 0
    currentSpecHash: sha256:885947ff9100a0e9292c6db1790245027c859d6cb76ecc51ccc343788f218880
    hashComputed: true
    healthAssessed: true
    healthScore: 0
    postRemediationSpecHash: sha256:885947ff9100a0e9292c6db1790245027c859d6cb76ecc51ccc343788f218880
  conditions:
  - lastTransitionTime: "2026-10-03T15:22:16Z"
    message: Post-remediation spec hash captured
    observedGeneration: 1
    reason: PostHashCaptured
    status: "True"
    type: PostHashCaptured
  - lastTransitionTime: "2026-10-03T15:22:16Z"
    message: Target resource spec unchanged since post-remediation hash
    observedGeneration: 1
    reason: SpecUnchanged
    status: "True"
    type: SpecIntegrity
  - lastTransitionTime: "2026-10-03T15:24:16Z"
    message: Assessment completed
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-03T15:24:16Z"
    message: 'Assessment completed: MetricsTimedOut'
    observedGeneration: 1
    reason: MetricsTimedOut
    status: "True"
    type: AssessmentComplete
  message: 'Assessment completed: MetricsTimedOut'
  phase: Completed
  prometheusCheckAfter: "2026-10-03T15:22:16Z"
  validityDeadline: "2026-10-03T15:24:16Z"
