apiVersion: kubernaut.ai/v1alpha1
kind: RemediationRequest
metadata:
  annotations:
    kubernaut.ai/created-at: "2026-10-03T15:14:03Z"
  creationTimestamp: "2026-10-03T15:14:03Z"
  generation: 1
  labels:
    app.kubernetes.io/component: remediation
    app.kubernetes.io/managed-by: gateway-service
  name: rr-825b58c1ca42-c9f71ce7
  namespace: kubernaut-system
  resourceVersion: "170845"
  uid: 60097afd-0c5b-4fca-b440-deb7de6490f0
spec:
  clusterID: remote-cluster
  firingTime: "2026-10-03T15:13:57Z"
  originalPayload: |
    {"receiver":"gateway-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-5brk4","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"3bb136d7-e32a-4c25-87ea-50e3cad39108"},"annotations":{"description":"One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n","summary":"Pod batch-processor-6547d9848-5brk4 in namespace demo-scheduler has been unscheduled for an extended period.\n"},"startsAt":"2026-10-03T15:13:57.46Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-scheduler%22%2Cphase%3D%22Pending%22%7D+%3D%3D+1\u0026g0.tab=1","fingerprint":"be489c1f4f86a6c3"},{"status":"firing","labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-jc2h8","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"2de277d6-2ae9-4baa-bf5c-2281cf9136c4"},"annotations":{"description":"One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n","summary":"Pod batch-processor-6547d9848-jc2h8 in namespace demo-scheduler has been unscheduled for an extended period.\n"},"startsAt":"2026-10-03T15:13:57.46Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-scheduler%22%2Cphase%3D%22Pending%22%7D+%3D%3D+1\u0026g0.tab=1","fingerprint":"9026a58a70eb3c42"}],"notification_reason":"first notification","groupLabels":{},"commonLabels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning"},"commonAnnotations":{"description":"One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n"},"routeLabels":{},"externalURL":"http://alertmanager-5fbfdbf7b6-b5tz7:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
  providerData: '{"labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-5brk4","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"3bb136d7-e32a-4c25-87ea-50e3cad39108"},"namespace":"demo-scheduler"}'
  receivedTime: "2026-10-03T15:14:03Z"
  severity: warning
  signalAnnotations:
    description: |
      One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.
    summary: |
      Pod batch-processor-6547d9848-5brk4 in namespace demo-scheduler has been unscheduled for an extended period.
  signalFingerprint: 825b58c1ca422c19842a3fd9989ca18d0226c34aafd140bf6b4b8a02da73c22a
  signalLabels:
    alertname: KubePodNotScheduled
    cluster: remote-cluster
    container: kube-state-metrics
    endpoint: http-metrics
    instance: 10.244.0.9:8080
    job: kube-state-metrics
    namespace: demo-scheduler
    phase: Pending
    pod: batch-processor-6547d9848-5brk4
    prometheus: monitoring/fleet-spoke
    service: kube-state-metrics
    severity: warning
    uid: 3bb136d7-e32a-4c25-87ea-50e3cad39108
  signalName: KubePodNotScheduled
  signalSource: prometheus
  signalType: alert
  targetResource:
    kind: Deployment
    name: batch-processor
    namespace: demo-scheduler
  targetType: kubernetes
status:
  completedAt: "2026-10-03T15:24:16Z"
  completionStatus:
    notificationRequestRefs:
    - apiVersion: notification.kubernaut.ai/v1alpha1
      kind: NotificationRequest
      name: nr-completion-rr-825b58c1ca42-c9f71ce7
      namespace: kubernaut-system
      uid: 50df73d5-9c93-4794-8bfe-c2153f03fe22
    notificationStatus: Sent
    outcome: Inconclusive
  conditions:
  - lastTransitionTime: "2026-10-03T15:14:03Z"
    message: SignalProcessing CRD sp-rr-825b58c1ca42-c9f71ce7 created successfully
    observedGeneration: 1
    reason: SignalProcessingCreated
    status: "True"
    type: SignalProcessingReady
  - lastTransitionTime: "2026-10-03T15:17:16Z"
    message: Remediation completed, verifying effectiveness
    observedGeneration: 1
    reason: Verifying
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-03T15:14:03Z"
    message: AIAnalysis CRD ai-rr-825b58c1ca42-c9f71ce7 created successfully
    observedGeneration: 1
    reason: AIAnalysisCreated
    status: "True"
    type: AIAnalysisReady
  - lastTransitionTime: "2026-10-03T15:14:03Z"
    message: SignalProcessing completed successfully
    observedGeneration: 1
    reason: SignalProcessingSucceeded
    status: "True"
    type: SignalProcessingComplete
  - lastTransitionTime: "2026-10-03T15:16:34Z"
    message: AIAnalysis completed successfully
    observedGeneration: 1
    reason: AIAnalysisSucceeded
    status: "True"
    type: AIAnalysisComplete
  - lastTransitionTime: "2026-10-03T15:16:34Z"
    message: Pre-remediation hash captured
    observedGeneration: 1
    reason: HashCaptured
    status: "True"
    type: PreRemediationHashCaptured
  - lastTransitionTime: "2026-10-03T15:16:34Z"
    message: WorkflowExecution CRD we-rr-825b58c1ca42-c9f71ce7 created successfully
    observedGeneration: 1
    reason: WorkflowExecutionCreated
    status: "True"
    type: WorkflowExecutionReady
  - lastTransitionTime: "2026-10-03T15:17:16Z"
    message: WorkflowExecution completed successfully
    observedGeneration: 1
    reason: WorkflowSucceeded
    status: "True"
    type: WorkflowExecutionComplete
  - lastTransitionTime: "2026-10-03T15:24:16Z"
    message: 'Effectiveness assessment completed (reason: MetricsTimedOut)'
    observedGeneration: 1
    reason: AssessmentCompleted
    status: "True"
    type: EffectivenessAssessed
  - lastTransitionTime: "2026-10-03T15:24:16Z"
    message: Notification delivered successfully
    observedGeneration: 1
    reason: DeliverySucceeded
    status: "True"
    type: NotificationDelivered
  deduplication:
    firstSeenAt: "2026-10-03T15:14:03Z"
    lastSeenAt: "2026-10-03T15:14:24Z"
    occurrenceCount: 6
  observedGeneration: 1
  operatorAudit:
    lastModifiedAt: "2026-10-03T15:14:03Z"
    lastModifiedBy: system:serviceaccount:kubernaut-system:remediationorchestrator-controller
    preRemediationSpecHash: sha256:885947ff9100a0e9292c6db1790245027c859d6cb76ecc51ccc343788f218880
  overallPhase: Completed
  phaseProgress:
    aiAnalysisRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: AIAnalysis
      name: ai-rr-825b58c1ca42-c9f71ce7
      namespace: kubernaut-system
    analyzingStartTime: "2026-10-03T15:14:04Z"
    effectivenessAssessmentRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: EffectivenessAssessment
      name: ea-rr-825b58c1ca42-c9f71ce7
      namespace: kubernaut-system
    executingStartTime: "2026-10-03T15:16:34Z"
    processingStartTime: "2026-10-03T15:14:03Z"
    signalProcessingRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: SignalProcessing
      name: sp-rr-825b58c1ca42-c9f71ce7
      namespace: kubernaut-system
    verificationDeadline: "2026-10-03T15:24:46Z"
    workflowExecutionRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: WorkflowExecution
      name: we-rr-825b58c1ca42-c9f71ce7
      namespace: kubernaut-system
  retentionExpiryTime: "2026-10-04T15:24:16Z"
  routingStatus:
    consecutiveFailureCount: 1
    nextAllowedExecution: "2026-10-03T15:25:16Z"
  startTime: "2026-10-03T15:14:03Z"
  timeoutConfig:
    analyzing: 10m0s
    executing: 30m0s
    global: 1h0m0s
    processing: 5m0s
  workflowSelection:
    confidence: "0.78"
    remediationTarget:
      apiVersion: apps/v1
      kind: Deployment
      name: batch-processor
      namespace: demo-scheduler
    selectedWorkflowRef:
      executionBundle: quay.io/kubernaut-cicd/test-workflows/remove-taint-job@sha256:2121ecf1001f6b95b7aeabda1fd4e2eb9eba9052a514a18a1e0f841d9958d561
      version: 1.6.3
      workflowId: 51247c9a-179f-54b8-b2fa-ece9fb80ef17
    signalTargetDisplay: Deployment/batch-processor
    targetDisplay: Deployment/batch-processor
    workflowDisplayName: RemoveTaint/remove-taint-v1
