apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - connection-leaker.yaml
  - app-workloads.yaml
  - servicemonitor.yaml
  - prometheus-rule.yaml
