apiVersion: kubernaut.ai/v1alpha1
kind: RemediationRequest
metadata:
  annotations:
    kubernaut.ai/created-at: "2026-10-02T04:41:20Z"
  creationTimestamp: "2026-10-02T04:41:20Z"
  generation: 1
  labels:
    app.kubernetes.io/component: remediation
    app.kubernetes.io/managed-by: gateway-service
  name: rr-4309bc63be09-59d3c641
  namespace: kubernaut-system
  resourceVersion: "89478"
  uid: 67a55c99-d7f5-445f-9a45-7ad35905f07a
spec:
  clusterID: remote-cluster
  firingTime: "2026-10-02T04:41:14Z"
  originalPayload: |
    {"receiver":"gateway-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"ContainerOOMKilling","cluster":"remote-cluster","container":"worker","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-analytics","pod":"analytics-worker-776f4b975b-kxg8w","prometheus":"monitoring/fleet-spoke","reason":"OOMKilled","service":"kube-state-metrics","severity":"critical","uid":"3ed5259b-f96a-4541-b41c-6c7d1c7fd9ad"},"annotations":{"description":"A container in namespace demo-analytics was terminated due to exceeding memory limits.","summary":"Container worker in pod analytics-worker-776f4b975b-kxg8w was OOMKilled."},"startsAt":"2026-10-02T00:00:29.963Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_container_status_last_terminated_reason%7Bnamespace%3D%22demo-analytics%22%2Creason%3D%22OOMKilled%22%7D+%3E+0\u0026g0.tab=1","fingerprint":"103f9e2beb830951"},{"status":"firing","labels":{"alertname":"KubePodCrashLooping","cluster":"remote-cluster","container":"api-gateway","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-ingress","pod":"api-gateway-67b95bfdbf-f9hwq","prometheus":"monitoring/fleet-spoke","reason":"CrashLoopBackOff","service":"kube-state-metrics","severity":"critical","uid":"09907e74-66e9-4e3b-9936-a9f12cfdcb74"},"annotations":{"description":"Multiple pods in the api-gateway deployment are crashing simultaneously.\n","summary":"Container api-gateway in pod api-gateway-67b95bfdbf-f9hwq is in CrashLoopBackOff.\n"},"startsAt":"2026-10-02T04:41:14.755Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=max_over_time%28kube_pod_container_status_waiting_reason%7Bcontainer%3D%22api-gateway%22%2Cnamespace%3D%22demo-ingress%22%2Creason%3D%22CrashLoopBackOff%22%7D%5B2m%5D%29+%3E+0\u0026g0.tab=1","fingerprint":"81177b5842f74433"},{"status":"firing","labels":{"alertname":"KubePodCrashLooping","cluster":"remote-cluster","container":"api-gateway","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-ingress","pod":"api-gateway-67b95bfdbf-l8ph9","prometheus":"monitoring/fleet-spoke","reason":"CrashLoopBackOff","service":"kube-state-metrics","severity":"critical","uid":"1b92668b-c96c-4cea-ae70-5c64fd1bbb02"},"annotations":{"description":"Multiple pods in the api-gateway deployment are crashing simultaneously.\n","summary":"Container api-gateway in pod api-gateway-67b95bfdbf-l8ph9 is in CrashLoopBackOff.\n"},"startsAt":"2026-10-02T04:41:14.755Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=max_over_time%28kube_pod_container_status_waiting_reason%7Bcontainer%3D%22api-gateway%22%2Cnamespace%3D%22demo-ingress%22%2Creason%3D%22CrashLoopBackOff%22%7D%5B2m%5D%29+%3E+0\u0026g0.tab=1","fingerprint":"82a391662715dd19"},{"status":"firing","labels":{"alertname":"KubePodCrashLooping","cluster":"remote-cluster","container":"api-gateway","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-ingress","pod":"api-gateway-67b95bfdbf-wktck","prometheus":"monitoring/fleet-spoke","reason":"CrashLoopBackOff","service":"kube-state-metrics","severity":"critical","uid":"36774ab9-8958-449e-a401-8293f0d43812"},"annotations":{"description":"Multiple pods in the api-gateway deployment are crashing simultaneously.\n","summary":"Container api-gateway in pod api-gateway-67b95bfdbf-wktck is in CrashLoopBackOff.\n"},"startsAt":"2026-10-02T04:41:14.755Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=max_over_time%28kube_pod_container_status_waiting_reason%7Bcontainer%3D%22api-gateway%22%2Cnamespace%3D%22demo-ingress%22%2Creason%3D%22CrashLoopBackOff%22%7D%5B2m%5D%29+%3E+0\u0026g0.tab=1","fingerprint":"287fa0aeb94d502f"},{"status":"firing","labels":{"alertname":"KubeDeploymentRolloutStuck","cluster":"remote-cluster","condition":"Progressing","container":"kube-state-metrics","deployment":"checkout-api","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-shipping","pod":"kube-state-metrics-78f5b5f8f9-6jj6k","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical","status":"false"},"annotations":{"description":"A deployment rollout in namespace demo-shipping has stalled. New pods are not reaching Ready state.\n","summary":"Deployment checkout-api in namespace demo-shipping rollout is not progressing.\n"},"startsAt":"2026-10-02T00:00:23.285Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_deployment_status_condition%7Bcondition%3D%22Progressing%22%2Cdeployment%3D%22checkout-api%22%2Cnamespace%3D%22demo-shipping%22%2Cstatus%3D%22false%22%7D+%3D%3D+1\u0026g0.tab=1","fingerprint":"c60f8b2a2b9428f9"}],"notification_reason":"new alerts added","groupLabels":{},"commonLabels":{"cluster":"remote-cluster","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical"},"commonAnnotations":{},"routeLabels":{},"externalURL":"http://alertmanager-78446d564f-lzmxq:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
  providerData: '{"labels":{"alertname":"KubePodCrashLooping","cluster":"remote-cluster","container":"api-gateway","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-ingress","pod":"api-gateway-67b95bfdbf-f9hwq","prometheus":"monitoring/fleet-spoke","reason":"CrashLoopBackOff","service":"kube-state-metrics","severity":"critical","uid":"09907e74-66e9-4e3b-9936-a9f12cfdcb74"},"namespace":"demo-ingress"}'
  receivedTime: "2026-10-02T04:41:20Z"
  severity: critical
  signalAnnotations:
    description: |
      Multiple pods in the api-gateway deployment are crashing simultaneously.
    summary: |
      Container api-gateway in pod api-gateway-67b95bfdbf-f9hwq is in CrashLoopBackOff.
  signalFingerprint: 4309bc63be0928489c55f1846a36c4cc92435f5e9dd6b1fe9cb4e27dbdfb1040
  signalLabels:
    alertname: KubePodCrashLooping
    cluster: remote-cluster
    container: api-gateway
    endpoint: http-metrics
    instance: 10.244.0.9:8080
    job: kube-state-metrics
    namespace: demo-ingress
    pod: api-gateway-67b95bfdbf-f9hwq
    prometheus: monitoring/fleet-spoke
    reason: CrashLoopBackOff
    service: kube-state-metrics
    severity: critical
    uid: 09907e74-66e9-4e3b-9936-a9f12cfdcb74
  signalName: KubePodCrashLooping
  signalSource: prometheus
  signalType: alert
  targetResource:
    kind: Deployment
    name: api-gateway
    namespace: demo-ingress
  targetType: kubernetes
status:
  completedAt: "2026-10-02T04:44:39Z"
  completionStatus:
    failurePhase: WorkflowExecution
    failureReason: WorkflowExecution failed
    notificationRequestRefs:
    - apiVersion: notification.kubernaut.ai/v1alpha1
      kind: NotificationRequest
      name: nr-manual-review-rr-4309bc63be09-59d3c641
      namespace: kubernaut-system
    notificationStatus: Sent
  conditions:
  - lastTransitionTime: "2026-10-02T04:41:21Z"
    message: SignalProcessing CRD sp-rr-4309bc63be09-59d3c641 created successfully
    observedGeneration: 1
    reason: SignalProcessingCreated
    status: "True"
    type: SignalProcessingReady
  - lastTransitionTime: "2026-10-02T04:41:21Z"
    message: Remediation failed
    observedGeneration: 1
    reason: RemediationFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2026-10-02T04:41:21Z"
    message: AIAnalysis CRD ai-rr-4309bc63be09-59d3c641 created successfully
    observedGeneration: 1
    reason: AIAnalysisCreated
    status: "True"
    type: AIAnalysisReady
  - lastTransitionTime: "2026-10-02T04:41:21Z"
    message: SignalProcessing completed successfully
    observedGeneration: 1
    reason: SignalProcessingSucceeded
    status: "True"
    type: SignalProcessingComplete
  - lastTransitionTime: "2026-10-02T04:42:27Z"
    message: AIAnalysis completed successfully
    observedGeneration: 1
    reason: AIAnalysisSucceeded
    status: "True"
    type: AIAnalysisComplete
  - lastTransitionTime: "2026-10-02T04:42:29Z"
    message: Pre-remediation hash captured
    observedGeneration: 1
    reason: HashCaptured
    status: "True"
    type: PreRemediationHashCaptured
  - lastTransitionTime: "2026-10-02T04:42:29Z"
    message: WorkflowExecution CRD we-rr-4309bc63be09-59d3c641 created successfully
    observedGeneration: 1
    reason: WorkflowExecutionCreated
    status: "True"
    type: WorkflowExecutionReady
  - lastTransitionTime: "2026-10-02T04:44:39Z"
    message: WorkflowExecution failed
    observedGeneration: 1
    reason: WorkflowFailed
    status: "False"
    type: WorkflowExecutionComplete
  - lastTransitionTime: "2026-10-02T04:44:39Z"
    message: Notification delivered successfully
    observedGeneration: 1
    reason: DeliverySucceeded
    status: "True"
    type: NotificationDelivered
  deduplication:
    firstSeenAt: "2026-10-02T04:41:21Z"
    lastSeenAt: "2026-10-02T04:41:21Z"
    occurrenceCount: 3
  observedGeneration: 1
  operatorAudit:
    lastModifiedAt: "2026-10-02T04:41:20Z"
    lastModifiedBy: system:serviceaccount:kubernaut-system:remediationorchestrator-controller
    preRemediationSpecHash: sha256:282d5cbf425d51a92766afcab45606aa4d9ed1019bf8dba6174303eb9eea628d
  overallPhase: Failed
  phaseProgress:
    aiAnalysisRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: AIAnalysis
      name: ai-rr-4309bc63be09-59d3c641
      namespace: kubernaut-system
    analyzingStartTime: "2026-10-02T04:41:21Z"
    executingStartTime: "2026-10-02T04:42:30Z"
    processingStartTime: "2026-10-02T04:41:21Z"
    signalProcessingRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: SignalProcessing
      name: sp-rr-4309bc63be09-59d3c641
      namespace: kubernaut-system
    workflowExecutionRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: WorkflowExecution
      name: we-rr-4309bc63be09-59d3c641
      namespace: kubernaut-system
  retentionExpiryTime: "2026-10-03T04:44:39Z"
  routingStatus:
    consecutiveFailureCount: 1
    nextAllowedExecution: "2026-10-02T04:45:45Z"
  startTime: "2026-10-02T04:41:20Z"
  timeoutConfig:
    analyzing: 10m0s
    executing: 30m0s
    global: 1h0m0s
    processing: 5m0s
  workflowSelection:
    confidence: "0.96"
    remediationTarget:
      apiVersion: apps/v1
      kind: Deployment
      name: api-gateway
      namespace: demo-ingress
    selectedWorkflowRef:
      executionBundle: quay.io/kubernaut-cicd/test-workflows/fix-image-reference-job@sha256:0c3594fdf6d737b18a6aae6c63db677baa8673c7401ae3057ccbd7324819e0ae
      version: 1.6.3
      workflowId: 45c70620-7fc4-5150-9165-ddc643b9281f
    signalTargetDisplay: Deployment/api-gateway
    targetDisplay: Deployment/api-gateway
    workflowDisplayName: RollbackDeployment/fix-image-reference-v1
