apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-app-alerts
  namespace: demo-analytics
  labels:
    release: prometheus
spec:
  groups:
  - name: demo-app
    rules:
    - alert: ContainerOOMKilling
      expr: |
        kube_pod_container_status_last_terminated_reason{
          reason="OOMKilled",
          namespace="demo-analytics"
        } > 0
      for: 30s
      labels:
        severity: critical
        namespace: demo-analytics
        pod: '{{ $labels.pod }}'
        container: '{{ $labels.container }}'
      annotations:
        summary: "Container {{ $labels.container }} in pod {{ $labels.pod }} was OOMKilled."
        description: "A container in namespace {{ $labels.namespace }} was terminated due to exceeding memory limits."
