apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-02T23:04:37Z"
    generateName: worker-68f8898c86-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 68f8898c86
    name: worker-68f8898c86-4rn8v
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-68f8898c86
      uid: 46ed10bd-7850-49fd-8ab8-9147642d2113
    resourceVersion: "27609"
    uid: 550b7f25-e046-4b00-b50c-625df26cd46d
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wmgcl
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-wmgcl
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:42Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:42Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://435f4426897b839fa991acc6e3a2c1492040fbe42928573fccc958f8b027a192
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: worker
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-02T23:04:39Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wmgcl
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.70
    podIPs:
    - ip: 10.244.0.70
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T23:04:38Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-02T23:04:38Z"
    generateName: worker-68f8898c86-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 68f8898c86
    name: worker-68f8898c86-6x77r
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-68f8898c86
      uid: 46ed10bd-7850-49fd-8ab8-9147642d2113
    resourceVersion: "27614"
    uid: e3604467-1502-44a4-9bfe-e47c3db56877
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pq42d
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-pq42d
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:42Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:42Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:04:38Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://db4f8b592b9a5fefc9a3f73eeed1b1a1b97a0638deb29f1b02d9ff104a95791f
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: worker
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-02T23:04:39Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pq42d
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.69
    podIPs:
    - ip: 10.244.0.69
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T23:04:38Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2026-10-02T19:05:03-04:00"
    creationTimestamp: "2026-10-02T23:05:03Z"
    generateName: worker-69bc5b4c79-
    generation: 1
    labels:
      app: worker
      pod-template-hash: 69bc5b4c79
    name: worker-69bc5b4c79-4xc8c
    namespace: demo-workers
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: worker-69bc5b4c79
      uid: 3ce302bc-28e8-47f4-a3ff-671e1081bb2d
    resourceVersion: "38865"
    uid: e27b97bb-ae19-4b32-b5ba-80ef11b8e098
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: worker
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-phwfq
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: worker-config
      name: config
    - name: kube-api-access-phwfq
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:05:03Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:05:03Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:05:03Z"
      message: 'containers with unready status: [worker]'
      observedGeneration: 1
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:05:03Z"
      message: 'containers with unready status: [worker]'
      observedGeneration: 1
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-02T23:05:03Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://72df586d29490f32487be2caba38c31c334ac00fa024aee02463189a53620872
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState:
        terminated:
          containerID: containerd://72df586d29490f32487be2caba38c31c334ac00fa024aee02463189a53620872
          exitCode: 1
          finishedAt: "2026-10-03T00:32:22Z"
          reason: Error
          startedAt: "2026-10-03T00:32:22Z"
      name: worker
      ready: false
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 22
      started: false
      state:
        waiting:
          message: back-off 5m0s restarting failed container=worker pod=worker-69bc5b4c79-4xc8c_demo-workers(e27b97bb-ae19-4b32-b5ba-80ef11b8e098)
          reason: CrashLoopBackOff
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-phwfq
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.12
    hostIPs:
    - ip: 10.89.0.12
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.71
    podIPs:
    - ip: 10.244.0.71
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-02T23:05:03Z"
kind: List
metadata:
  resourceVersion: ""
