apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kubernaut.ai/business-unit":"engineering","kubernaut.ai/component":"backend-api","kubernaut.ai/criticality":"high","kubernaut.ai/environment":"production","kubernaut.ai/managed":"true","kubernaut.ai/service-owner":"backend-team","kubernaut.ai/sla-tier":"tier-1"},"name":"demo-workers"}}
  creationTimestamp: "2026-10-02T23:04:37Z"
  labels:
    kubernaut.ai/business-unit: engineering
    kubernaut.ai/component: backend-api
    kubernaut.ai/criticality: high
    kubernaut.ai/environment: production
    kubernaut.ai/managed: "true"
    kubernaut.ai/service-owner: backend-team
    kubernaut.ai/sla-tier: tier-1
    kubernetes.io/metadata.name: demo-workers
  name: demo-workers
  resourceVersion: "27551"
  uid: 33af6871-8a4b-43c5-93ee-dd4059fa53a2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
