apiVersion: kubernaut.ai/v1alpha1
kind: RemediationRequest
metadata:
  annotations:
    kubernaut.ai/created-at: "2026-10-03T03:19:48Z"
  creationTimestamp: "2026-10-03T03:19:48Z"
  generation: 1
  labels:
    app.kubernetes.io/component: remediation
    app.kubernetes.io/managed-by: gateway-service
  name: rr-157ae5efb2f2-fd846b3b
  namespace: kubernaut-system
  resourceVersion: "75705"
  uid: 8dbd04a0-2c39-46f5-949b-e232be5fdbc2
spec:
  clusterID: remote-cluster
  firingTime: "2026-10-03T03:19:46Z"
  originalPayload: |
    {"receiver":"gateway-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.61:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-1","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-1 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-1 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-02T22:46:56.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"85cc95ea67d9c618"},{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.62:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-0","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-0 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-0 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-02T22:46:56.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"c83d84e9049d4c1c"},{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.63:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-2","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-2 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-2 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-02T22:47:11.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"5965aeabd831c951"},{"status":"firing","labels":{"alertname":"KubePodSchedulingFailed","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-loadtest","phase":"Pending","pod":"web-cluster-56c7c6856b-qkwzs","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical","uid":"09810787-80d6-4efe-a33e-89ce31a43adc"},"annotations":{"description":"Workload pods in namespace demo-loadtest have not been scheduled. Service capacity may be degraded.\n","summary":"One or more pods in namespace demo-loadtest are stuck in Pending state.\n"},"startsAt":"2026-10-03T03:19:46.851Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-loadtest%22%2Cphase%3D%22Pending%22%7D+%3E+0\u0026g0.tab=1","fingerprint":"3a3bba0d53722b2d"},{"status":"firing","labels":{"alertname":"KubePodSchedulingFailed","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-loadtest","phase":"Pending","pod":"web-cluster-56c7c6856b-wf8d6","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical","uid":"1a2fc3af-dc11-4df7-8b5d-ba6c812a47d9"},"annotations":{"description":"Workload pods in namespace demo-loadtest have not been scheduled. Service capacity may be degraded.\n","summary":"One or more pods in namespace demo-loadtest are stuck in Pending state.\n"},"startsAt":"2026-10-03T03:19:46.851Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-loadtest%22%2Cphase%3D%22Pending%22%7D+%3E+0\u0026g0.tab=1","fingerprint":"d00cbac0049f4a8b"},{"status":"firing","labels":{"alertname":"KubePodSchedulingFailed","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-loadtest","phase":"Pending","pod":"web-cluster-56c7c6856b-wxdnx","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical","uid":"49ac6df9-87d3-43d9-b8d6-a5e37a6d1cda"},"annotations":{"description":"Workload pods in namespace demo-loadtest have not been scheduled. Service capacity may be degraded.\n","summary":"One or more pods in namespace demo-loadtest are stuck in Pending state.\n"},"startsAt":"2026-10-03T03:19:46.851Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-loadtest%22%2Cphase%3D%22Pending%22%7D+%3E+0\u0026g0.tab=1","fingerprint":"51881e10fe666fd0"}],"notification_reason":"new alerts added","groupLabels":{},"commonLabels":{"cluster":"remote-cluster","prometheus":"monitoring/fleet-spoke","severity":"critical"},"commonAnnotations":{},"routeLabels":{},"externalURL":"http://alertmanager-566cd8d6fb-5fshl:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
  providerData: '{"labels":{"alertname":"KubePodSchedulingFailed","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-loadtest","phase":"Pending","pod":"web-cluster-56c7c6856b-qkwzs","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"critical","uid":"09810787-80d6-4efe-a33e-89ce31a43adc"},"namespace":"demo-loadtest"}'
  receivedTime: "2026-10-03T03:19:47Z"
  severity: critical
  signalAnnotations:
    description: |
      Workload pods in namespace demo-loadtest have not been scheduled. Service capacity may be degraded.
    summary: |
      One or more pods in namespace demo-loadtest are stuck in Pending state.
  signalFingerprint: 157ae5efb2f22cc19a87b95b5d08e06b84edbbcecd3e434db170ed6e00802d66
  signalLabels:
    alertname: KubePodSchedulingFailed
    cluster: remote-cluster
    container: kube-state-metrics
    endpoint: http-metrics
    instance: 10.244.0.9:8080
    job: kube-state-metrics
    namespace: demo-loadtest
    phase: Pending
    pod: web-cluster-56c7c6856b-qkwzs
    prometheus: monitoring/fleet-spoke
    service: kube-state-metrics
    severity: critical
    uid: 09810787-80d6-4efe-a33e-89ce31a43adc
  signalName: KubePodSchedulingFailed
  signalSource: prometheus
  signalType: alert
  targetResource:
    kind: Deployment
    name: web-cluster
    namespace: demo-loadtest
  targetType: kubernetes
status:
  completedAt: "2026-10-03T03:26:34Z"
  completionStatus:
    notificationRequestRefs:
    - apiVersion: notification.kubernaut.ai/v1alpha1
      kind: NotificationRequest
      name: nr-completion-rr-157ae5efb2f2-fd846b3b
      namespace: kubernaut-system
    notificationStatus: Sent
    outcome: Remediated
  conditions:
  - lastTransitionTime: "2026-10-03T03:19:48Z"
    message: SignalProcessing CRD sp-rr-157ae5efb2f2-fd846b3b created successfully
    observedGeneration: 1
    reason: SignalProcessingCreated
    status: "True"
    type: SignalProcessingReady
  - lastTransitionTime: "2026-10-03T03:21:34Z"
    message: Remediation completed, verifying effectiveness
    observedGeneration: 1
    reason: Verifying
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-03T03:19:49Z"
    message: AIAnalysis CRD ai-rr-157ae5efb2f2-fd846b3b created successfully
    observedGeneration: 1
    reason: AIAnalysisCreated
    status: "True"
    type: AIAnalysisReady
  - lastTransitionTime: "2026-10-03T03:19:49Z"
    message: SignalProcessing completed successfully
    observedGeneration: 1
    reason: SignalProcessingSucceeded
    status: "True"
    type: SignalProcessingComplete
  - lastTransitionTime: "2026-10-03T03:21:23Z"
    message: AIAnalysis completed successfully
    observedGeneration: 1
    reason: AIAnalysisSucceeded
    status: "True"
    type: AIAnalysisComplete
  - lastTransitionTime: "2026-10-03T03:21:23Z"
    message: Pre-remediation hash captured
    observedGeneration: 1
    reason: HashCaptured
    status: "True"
    type: PreRemediationHashCaptured
  - lastTransitionTime: "2026-10-03T03:21:23Z"
    message: WorkflowExecution CRD we-rr-157ae5efb2f2-fd846b3b created successfully
    observedGeneration: 1
    reason: WorkflowExecutionCreated
    status: "True"
    type: WorkflowExecutionReady
  - lastTransitionTime: "2026-10-03T03:21:34Z"
    message: WorkflowExecution completed successfully
    observedGeneration: 1
    reason: WorkflowSucceeded
    status: "True"
    type: WorkflowExecutionComplete
  - lastTransitionTime: "2026-10-03T03:26:34Z"
    message: 'Effectiveness assessment completed (reason: Full)'
    observedGeneration: 1
    reason: AssessmentCompleted
    status: "True"
    type: EffectivenessAssessed
  - lastTransitionTime: "2026-10-03T03:26:34Z"
    message: Notification delivered successfully
    observedGeneration: 1
    reason: DeliverySucceeded
    status: "True"
    type: NotificationDelivered
  deduplication:
    firstSeenAt: "2026-10-03T03:19:48Z"
    lastSeenAt: "2026-10-03T03:19:48Z"
    occurrenceCount: 3
  observedGeneration: 1
  operatorAudit:
    lastModifiedAt: "2026-10-03T03:19:48Z"
    lastModifiedBy: system:serviceaccount:kubernaut-system:remediationorchestrator-controller
    preRemediationSpecHash: sha256:111ed1bd76d07af138eca12a2c45a41d9045f9c429fa73cd3ed0aa377a74f223
  overallPhase: Completed
  phaseProgress:
    aiAnalysisRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: AIAnalysis
      name: ai-rr-157ae5efb2f2-fd846b3b
      namespace: kubernaut-system
    analyzingStartTime: "2026-10-03T03:19:49Z"
    effectivenessAssessmentRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: EffectivenessAssessment
      name: ea-rr-157ae5efb2f2-fd846b3b
      namespace: kubernaut-system
    executingStartTime: "2026-10-03T03:21:23Z"
    processingStartTime: "2026-10-03T03:19:48Z"
    signalProcessingRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: SignalProcessing
      name: sp-rr-157ae5efb2f2-fd846b3b
      namespace: kubernaut-system
    verificationDeadline: "2026-10-03T03:29:04Z"
    workflowExecutionRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: WorkflowExecution
      name: we-rr-157ae5efb2f2-fd846b3b
      namespace: kubernaut-system
  retentionExpiryTime: "2026-10-04T03:26:34Z"
  routingStatus: {}
  startTime: "2026-10-03T03:19:48Z"
  timeoutConfig:
    analyzing: 10m0s
    executing: 30m0s
    global: 1h0m0s
    processing: 5m0s
  workflowSelection:
    confidence: "0.95"
    remediationTarget:
      apiVersion: apps/v1
      kind: Deployment
      name: web-cluster
      namespace: demo-loadtest
    selectedWorkflowRef:
      executionBundle: quay.io/kubernaut-cicd/test-workflows/scale-replicas-job@sha256:8e7ce7de50a2115bb9d1f0a74ad27bf13f201ceb8cb98285edce9166f894f125
      version: 1.6.3
      workflowId: 4841e667-eac3-5974-9a75-88f17de6ceae
    signalTargetDisplay: Deployment/web-cluster
    targetDisplay: Deployment/web-cluster
    workflowDisplayName: ScaleReplicas/scale-replicas-v1
