apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2026-10-01T19:26:26Z"
    labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: kubernaut-hub-control-plane
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
    name: kubernaut-hub-control-plane
    resourceVersion: "8933"
    uid: dabcc0bc-bf10-44cd-9683-f581b9c5fe63
  spec:
    podCIDR: 10.244.0.0/24
    podCIDRs:
    - 10.244.0.0/24
    providerID: kind://podman/kubernaut-hub/kubernaut-hub-control-plane
  status:
    addresses:
    - address: 10.89.0.4
      type: InternalIP
    - address: kubernaut-hub-control-plane
      type: Hostname
    allocatable:
      cpu: "6"
      ephemeral-storage: "99252940800"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      hugepages-32Mi: "0"
      hugepages-64Ki: "0"
      memory: 14233708Ki
      pods: "110"
    capacity:
      cpu: "6"
      ephemeral-storage: "99252940800"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      hugepages-32Mi: "0"
      hugepages-64Ki: "0"
      memory: 14233708Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2026-10-01T20:01:42Z"
      lastTransitionTime: "2026-10-01T19:26:26Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2026-10-01T20:01:42Z"
      lastTransitionTime: "2026-10-01T19:26:26Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2026-10-01T20:01:42Z"
      lastTransitionTime: "2026-10-01T19:26:26Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2026-10-01T20:01:42Z"
      lastTransitionTime: "2026-10-01T19:26:42Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    declaredFeatures:
    - ExtendWebSocketsToKubelet
    - InPlacePodLevelResourcesVerticalScaling
    - InPlacePodVerticalScalingInitContainers
    - RestartAllContainersOnContainerExits
    features:
      supplementalGroupsPolicy: true
    images:
    - names:
      - quay.io/keycloak/keycloak@sha256:0aae0de7fca85525f727d3354df17896092de8bb26ae4c12d89c77e5df8cbce4
      - quay.io/keycloak/keycloak:26.6.4
      sizeBytes: 264077219
    - names:
      - quay.io/argoproj/argocd@sha256:dd3f47d5a5e4da563a7a398506e892481b358a7cec50abdf320c71aa55904bfa
      - quay.io/argoproj/argocd:v3.5.3
      sizeBytes: 204754192
    - names:
      - quay.io/kubernaut-ai/kubernaut-console@sha256:9c6a336f4bf1d53184e497988778fc747d7fafa72376ef29b37dfeaa473ec1e2
      - quay.io/kubernaut-ai/kubernaut-console:1.6.0-rc20
      sizeBytes: 114072285
    - names:
      - docker.io/library/postgres@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
      - docker.io/library/postgres:16-alpine
      sizeBytes: 113905390
    - names:
      - docker.io/prom/prometheus@sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e
      - docker.io/prom/prometheus:latest
      sizeBytes: 104819933
    - names:
      - docker.io/library/import-2026-08-26@sha256:4fbbef5581e6ed60b96426e3786371b57da07f66e350b4ff2b0077413c2b0444
      - registry.k8s.io/kube-apiserver-arm64:v1.37.0
      - registry.k8s.io/kube-apiserver:v1.37.0
      sizeBytes: 97074036
    - names:
      - quay.io/thanos/thanos@sha256:4ec6df40fdb921de162677b321057caa8fb8324c65f4cfae9568ed55c4469e2c
      - quay.io/thanos/thanos:v0.37.2
      sizeBytes: 91152135
    - names:
      - docker.io/library/import-2026-08-26@sha256:dda35f6553455c1dde75aebfbb20759d24b7de776b884eb06415f242f276200c
      - registry.k8s.io/kube-controller-manager-arm64:v1.37.0
      - registry.k8s.io/kube-controller-manager:v1.37.0
      sizeBytes: 85081821
    - names:
      - docker.io/library/import-2026-08-26@sha256:d5e740cce95911da5590b633aae2f7f7e3370ec9d212d4dbbbf3bf19fa07551f
      - registry.k8s.io/kube-proxy-arm64:v1.37.0
      - registry.k8s.io/kube-proxy:v1.37.0
      sizeBytes: 84533341
    - names:
      - docker.io/bitnami/kubectl@sha256:6e2cdb22d6ab7264ea198c717f555e30536b54029d26c8781b9f25f78951b564
      sizeBytes: 71257358
    - names:
      - docker.io/envoyproxy/gateway-dev@sha256:c6c44d9f236a0092be677e1a111923590463f0711eea0e07ee8671300cc2e5d2
      - docker.io/envoyproxy/gateway-dev:latest
      sizeBytes: 70928918
    - names:
      - docker.io/envoyproxy/gateway@sha256:497df13b71f4e544c7e80414873041e291776c28cd788bcbee0d18421fa5db98
      - docker.io/envoyproxy/gateway:v1.8.1
      sizeBytes: 68130293
    - names:
      - docker.gitea.com/gitea@sha256:414ba5b2b1163480e9ed4213a989cd798579cfa88582a2359303273009b2b852
      - docker.gitea.com/gitea:1.27.0-rootless
      sizeBytes: 65193934
    - names:
      - ghcr.io/containers/kubernetes-mcp-server@sha256:4219880ffae9b61f5cf8e27c0536d4001336016a6af77dc5a63dfaf9ce938b97
      sizeBytes: 60798794
    - names:
      - docker.io/library/import-2026-08-26@sha256:2aa78b45454b3df79d15bf6a57b4f9871f11ce16c8b645109ba2310076d228dd
      - registry.k8s.io/kube-scheduler-arm64:v1.37.0
      - registry.k8s.io/kube-scheduler:v1.37.0
      sizeBytes: 59129947
    - names:
      - quay.io/kubernaut-ai/db-migrate@sha256:6b7611cd2e93d250707ab530b0a7512d3bb1b9f0a5521d445089df0f66b5d2a6
      - quay.io/kubernaut-ai/db-migrate:1.6.0-rc20
      sizeBytes: 52131622
    - names:
      - docker.io/bitnamilegacy/valkey-cluster@sha256:32869e769b7e554219f2ae527b85f4a4739574750beac63b895f5d09fc38f53b
      - docker.io/bitnamilegacy/valkey-cluster:8.1.3-debian-12-r3
      sizeBytes: 50708844
    - names:
      - docker.io/library/traefik@sha256:24841fe2de7304c149343d877d2923b4c8800a38ba015dea9174c23b20e344a0
      - docker.io/library/traefik:v3.7.13
      sizeBytes: 50026539
    - names:
      - ghcr.io/dexidp/dex@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
      - ghcr.io/dexidp/dex:v2.45.1
      sizeBytes: 43824487
    - names:
      - docker.io/envoyproxy/envoy@sha256:5484ea0d443278cacd66a20efb7f21db02bbcae12153b487ea470cdadf8a4d02
      - docker.io/envoyproxy/envoy:distroless-v1.38.1
      sizeBytes: 40600322
    - names:
      - docker.io/envoyproxy/ai-gateway-controller@sha256:8efefd3154d70205d6400055c93f982602f4ad7d9ffc32e97e6373d97e549ef0
      - docker.io/envoyproxy/ai-gateway-controller:v1.0.0
      sizeBytes: 40277938
    - names:
      - docker.io/prom/alertmanager@sha256:e9733bafb1bdef9b00e25a21f8f99dc26a22224bf16641ad754d1649f4c3357a
      - docker.io/prom/alertmanager:latest
      sizeBytes: 37767509
    - names:
      - docker.io/kindest/kindnetd:v20260820-69b56db7
      sizeBytes: 35652389
    - names:
      - docker.io/envoyproxy/ai-gateway-extproc@sha256:a38ac314b2b977561be3deaa722138ecb04a91e97122807cef08fccda880fa7e
      - docker.io/envoyproxy/ai-gateway-extproc:v1.0.0
      sizeBytes: 31545269
    - names:
      - quay.io/kubernaut-ai/apifrontend@sha256:17eaa216809dc6bef4984baec309e39f5205c8b8129ee34839a42b7902c98513
      - quay.io/kubernaut-ai/apifrontend:1.6.0-rc20
      sizeBytes: 28175597
    - names:
      - public.ecr.aws/docker/library/redis@sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba
      - public.ecr.aws/docker/library/redis:8.2.3-alpine
      sizeBytes: 27546824
    - names:
      - quay.io/kubernaut-ai/kubernautagent@sha256:8cf804f386be939eff3372497d98ca941f4f91714d27f3b91318e728bc35d615
      - quay.io/kubernaut-ai/kubernautagent:1.6.0-rc20
      sizeBytes: 26006126
    - names:
      - quay.io/kubernaut-ai/datastorage@sha256:479ffe81ba370c172d1980c39654a691f6973a217dfbe8e54d1582f79ea32bb9
      - quay.io/kubernaut-ai/datastorage:1.6.0-rc20
      sizeBytes: 21603526
    - names:
      - registry.k8s.io/coredns/coredns:v1.14.6
      sizeBytes: 21239459
    - names:
      - quay.io/kubernaut-ai/workflowexecution@sha256:e77ab6bb30d6ad75f924dac83c9ccb3b0ef82bc3a95fb6d3da4933e6bb7eb822
      - quay.io/kubernaut-ai/workflowexecution:1.6.0-rc20
      sizeBytes: 21235409
    - names:
      - quay.io/jetstack/cert-manager-controller@sha256:6c13d61e0348a5bc3477f8ea9a928624300b30d19b1c72a7d2b90372fc713db4
      - quay.io/jetstack/cert-manager-controller:v1.20.3
      sizeBytes: 21188877
    - names:
      - registry.k8s.io/etcd:3.7.0-0
      sizeBytes: 20455189
    - names:
      - quay.io/kubernaut-ai/gateway@sha256:172f431253256e285d6c7dbe691c1d3684bf12e057e3014fac28b831838ffd6e
      - quay.io/kubernaut-ai/gateway:1.6.0-rc20
      sizeBytes: 19644034
    - names:
      - quay.io/prometheus-operator/prometheus-operator@sha256:a001ed10a3823bbf2410ea347796d0e35ff8decd24fb98acbe7ab9e98d431c39
      - quay.io/prometheus-operator/prometheus-operator:v0.93.0
      sizeBytes: 18890907
    - names:
      - quay.io/oauth2-proxy/oauth2-proxy@sha256:10a1165743a192e1940b4708fb9647027185ce11a681a1c5519b442ff7f1f561
      - quay.io/oauth2-proxy/oauth2-proxy:v7.15.3
      sizeBytes: 18252499
    - names:
      - docker.io/valkey/valkey@sha256:081c2f5cb575efc901aa80ff9cdbd1ec6a301682fd35e1ebb4b0990a4a4a8507
      - docker.io/valkey/valkey:8-alpine
      sizeBytes: 17940082
    - names:
      - quay.io/jetstack/cert-manager-webhook@sha256:a61e817632cebed3bb59a189327e786fa3fdd7597167d994a1848d98fd55848f
      - quay.io/jetstack/cert-manager-webhook:v1.20.3
      sizeBytes: 17459880
    - names:
      - quay.io/kubernaut-ai/signalprocessing@sha256:8d55f05b8473bf5fd59adbe99d7a900bbb05ecd88f7e3c8928957361054cf5d1
      - quay.io/kubernaut-ai/signalprocessing:1.6.0-rc20
      sizeBytes: 16479609
    - names:
      - quay.io/kubernaut-ai/aianalysis@sha256:efeeb6d272c84f81d29e80dbfd253ebd87710f6dc1e07009ee038257cfac0272
      - quay.io/kubernaut-ai/aianalysis:1.6.0-rc20
      sizeBytes: 16037041
    - names:
      - quay.io/jetstack/cert-manager-cainjector@sha256:06ad347fe0dc2eb84cc355c26f6752e05e87dceb6447f5cd29b963dd66dfd8bd
      - quay.io/jetstack/cert-manager-cainjector:v1.20.3
      sizeBytes: 14651291
    - names:
      - docker.io/kindest/local-path-provisioner:v20260820-69b56db7
      sizeBytes: 14217939
    - names:
      - ghcr.io/stakater/reloader@sha256:b253579350a835082cdad8d8736671cedaa0f8309437c894bd1bf1c2f0e0d45e
      - ghcr.io/stakater/reloader:v1.4.21
      sizeBytes: 13981851
    - names:
      - quay.io/kubernaut-ai/remediationorchestrator@sha256:2a1fe303267215cec4de3b13c4c4d9d63683e6970d5c93d5c5910d4f4a5a801b
      - quay.io/kubernaut-ai/remediationorchestrator:1.6.0-rc20
      sizeBytes: 13913627
    - names:
      - quay.io/kubernaut-ai/effectivenessmonitor@sha256:ee33961a25779a76be0bcd9bcb318b9e9c6c34a938685b8f92965842451261af
      - quay.io/kubernaut-ai/effectivenessmonitor:1.6.0-rc20
      sizeBytes: 13661590
    - names:
      - quay.io/kubernaut-ai/authwebhook@sha256:9da1338831a86afa9a3dbf1f1026c898a2d03d84f1f40203b087c7243bce2780
      - quay.io/kubernaut-ai/authwebhook:1.6.0-rc20
      sizeBytes: 13129009
    - names:
      - registry.k8s.io/kube-state-metrics/kube-state-metrics@sha256:639a1e2da549210adddc0391ff91e270e83f7873014aec53258462812f741e6f
      - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
      sizeBytes: 13123973
    - names:
      - quay.io/kubernaut-ai/notification@sha256:b0003fc81a5334ca0b50110c4490f5700141687d6dffe52fbb48203d4083bb79
      - quay.io/kubernaut-ai/notification:1.6.0-rc20
      sizeBytes: 13056132
    - names:
      - quay.io/prometheus-operator/prometheus-config-reloader@sha256:0ccb22ca9f3f6fd9f76ce95585d18bd2e363d421c534dde710be4bd13caa551d
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.93.0
      sizeBytes: 13032467
    - names:
      - quay.io/kubernaut-ai/fleetmetadatacache@sha256:c315aeb4afb2f71e9c5ba439c387c4925823513ef1a5225e9db7c4bc6937cc54
      - quay.io/kubernaut-ai/fleetmetadatacache:1.6.0-rc20
      sizeBytes: 11658904
    - names:
      - ghcr.io/jkroepke/kube-webhook-certgen@sha256:d0e80b2f62fe43bb5e1b96adc692132fb4522e802f4cf673c09b1f94722b8cb6
      - ghcr.io/jkroepke/kube-webhook-certgen:1.8.5
      sizeBytes: 7968652
    nodeInfo:
      architecture: arm64
      bootID: 108ae7a5-cd34-42ab-89ce-cd2357f6943e
      containerRuntimeVersion: containerd://2.3.4
      kernelVersion: 7.1.10-200.fc44.aarch64
      kubeProxyVersion: ""
      kubeletVersion: v1.37.0
      machineID: 38fac70565bd43aea5f0957041d51c76
      operatingSystem: linux
      osImage: Debian GNU/Linux 13 (trixie)
      runningInUserNamespace: true
      systemUUID: b80d41ca-2151-4be4-9124-a644bf103401
    runtimeHandlers:
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: ""
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: runc
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: test-handler
kind: List
metadata:
  resourceVersion: ""
