apiVersion: kubernaut.ai/v1alpha1
kind: RemediationRequest
metadata:
  annotations:
    kubernaut.ai/created-at: "2026-10-03T11:35:37Z"
  creationTimestamp: "2026-10-03T11:35:37Z"
  generation: 1
  labels:
    app.kubernetes.io/component: remediation
    app.kubernetes.io/managed-by: gateway-service
  name: rr-825b58c1ca42-ffa5cb04
  namespace: kubernaut-system
  resourceVersion: "147689"
  uid: 980a8bf3-0dd2-4596-9afd-6e7ba8492849
spec:
  clusterID: remote-cluster
  firingTime: "2026-10-03T11:35:35Z"
  originalPayload: |
    {"receiver":"gateway-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.61:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-1","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-1 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-1 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-03T11:26:41.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"85cc95ea67d9c618"},{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.62:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-0","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-0 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-0 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-03T11:26:41.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"c83d84e9049d4c1c"},{"status":"firing","labels":{"alertname":"EtcdHighFragmentationRatio","cluster":"remote-cluster","container":"etcd","endpoint":"metrics","instance":"10.244.0.63:2381","job":"etcd-headless","namespace":"demo-datastore","pod":"etcd-2","prometheus":"monitoring/fleet-spoke","service":"etcd-headless","severity":"critical"},"annotations":{"description":"Total allocated storage on etcd-2 is significantly larger than the storage currently holding live data. This gap may indicate stale space that has not yet been reclaimed.\n","summary":"Pod etcd-2 in namespace demo-datastore shows on-disk storage far exceeding active data size.\n"},"startsAt":"2026-10-03T11:26:41.768Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=%28etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+-+etcd_mvcc_db_total_size_in_use_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D%29+%2F+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+0.15+and+etcd_mvcc_db_total_size_in_bytes%7Bnamespace%3D%22demo-datastore%22%7D+%3E+1048576\u0026g0.tab=1","fingerprint":"5965aeabd831c951"},{"status":"firing","labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-fld9m","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"c287b842-432d-4daa-a2f2-aedac1fe7680"},"annotations":{"description":"One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n","summary":"Pod batch-processor-6547d9848-fld9m in namespace demo-scheduler has been unscheduled for an extended period.\n"},"startsAt":"2026-10-03T11:35:35.346Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-scheduler%22%2Cphase%3D%22Pending%22%7D+%3D%3D+1\u0026g0.tab=1","fingerprint":"f5c8defffcce760a"},{"status":"firing","labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-zkrkd","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"f811607a-46d3-4f53-b195-25dfb9bd0f89"},"annotations":{"description":"One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n","summary":"Pod batch-processor-6547d9848-zkrkd in namespace demo-scheduler has been unscheduled for an extended period.\n"},"startsAt":"2026-10-03T11:35:35.346Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_pod_status_phase%7Bnamespace%3D%22demo-scheduler%22%2Cphase%3D%22Pending%22%7D+%3D%3D+1\u0026g0.tab=1","fingerprint":"822d943cc0dcf444"}],"notification_reason":"new alerts added","groupLabels":{},"commonLabels":{"cluster":"remote-cluster","prometheus":"monitoring/fleet-spoke"},"commonAnnotations":{},"routeLabels":{},"externalURL":"http://alertmanager-5d5f986899-dxszb:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
  providerData: '{"labels":{"alertname":"KubePodNotScheduled","cluster":"remote-cluster","container":"kube-state-metrics","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-scheduler","phase":"Pending","pod":"batch-processor-6547d9848-fld9m","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"warning","uid":"c287b842-432d-4daa-a2f2-aedac1fe7680"},"namespace":"demo-scheduler"}'
  receivedTime: "2026-10-03T11:35:37Z"
  severity: warning
  signalAnnotations:
    description: |
      One or more pods in namespace demo-scheduler are in Pending state and have not been assigned to a node. Workload availability may be degraded.
    summary: |
      Pod batch-processor-6547d9848-fld9m in namespace demo-scheduler has been unscheduled for an extended period.
  signalFingerprint: 825b58c1ca422c19842a3fd9989ca18d0226c34aafd140bf6b4b8a02da73c22a
  signalLabels:
    alertname: KubePodNotScheduled
    cluster: remote-cluster
    container: kube-state-metrics
    endpoint: http-metrics
    instance: 10.244.0.9:8080
    job: kube-state-metrics
    namespace: demo-scheduler
    phase: Pending
    pod: batch-processor-6547d9848-fld9m
    prometheus: monitoring/fleet-spoke
    service: kube-state-metrics
    severity: warning
    uid: c287b842-432d-4daa-a2f2-aedac1fe7680
  signalName: KubePodNotScheduled
  signalSource: prometheus
  signalType: alert
  targetResource:
    kind: Deployment
    name: batch-processor
    namespace: demo-scheduler
  targetType: kubernetes
status:
  completedAt: "2026-10-03T11:44:26Z"
  completionStatus:
    notificationRequestRefs:
    - apiVersion: notification.kubernaut.ai/v1alpha1
      kind: NotificationRequest
      name: nr-completion-rr-825b58c1ca42-ffa5cb04
      namespace: kubernaut-system
      uid: 828b2efa-4cd7-4bc7-8aa3-faaaaa21d355
    notificationStatus: Sent
    outcome: Inconclusive
  conditions:
  - lastTransitionTime: "2026-10-03T11:35:37Z"
    message: SignalProcessing CRD sp-rr-825b58c1ca42-ffa5cb04 created successfully
    observedGeneration: 1
    reason: SignalProcessingCreated
    status: "True"
    type: SignalProcessingReady
  - lastTransitionTime: "2026-10-03T11:37:26Z"
    message: Remediation completed, verifying effectiveness
    observedGeneration: 1
    reason: Verifying
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-03T11:35:38Z"
    message: AIAnalysis CRD ai-rr-825b58c1ca42-ffa5cb04 created successfully
    observedGeneration: 1
    reason: AIAnalysisCreated
    status: "True"
    type: AIAnalysisReady
  - lastTransitionTime: "2026-10-03T11:35:38Z"
    message: SignalProcessing completed successfully
    observedGeneration: 1
    reason: SignalProcessingSucceeded
    status: "True"
    type: SignalProcessingComplete
  - lastTransitionTime: "2026-10-03T11:36:43Z"
    message: AIAnalysis completed successfully
    observedGeneration: 1
    reason: AIAnalysisSucceeded
    status: "True"
    type: AIAnalysisComplete
  - lastTransitionTime: "2026-10-03T11:36:44Z"
    message: Pre-remediation hash captured
    observedGeneration: 1
    reason: HashCaptured
    status: "True"
    type: PreRemediationHashCaptured
  - lastTransitionTime: "2026-10-03T11:36:44Z"
    message: WorkflowExecution CRD we-rr-825b58c1ca42-ffa5cb04 created successfully
    observedGeneration: 1
    reason: WorkflowExecutionCreated
    status: "True"
    type: WorkflowExecutionReady
  - lastTransitionTime: "2026-10-03T11:37:26Z"
    message: WorkflowExecution completed successfully
    observedGeneration: 1
    reason: WorkflowSucceeded
    status: "True"
    type: WorkflowExecutionComplete
  - lastTransitionTime: "2026-10-03T11:44:26Z"
    message: 'Effectiveness assessment completed (reason: MetricsTimedOut)'
    observedGeneration: 1
    reason: AssessmentCompleted
    status: "True"
    type: EffectivenessAssessed
  - lastTransitionTime: "2026-10-03T11:44:26Z"
    message: Notification delivered successfully
    observedGeneration: 1
    reason: DeliverySucceeded
    status: "True"
    type: NotificationDelivered
  deduplication:
    firstSeenAt: "2026-10-03T11:35:37Z"
    lastSeenAt: "2026-10-03T11:35:37Z"
    occurrenceCount: 2
  observedGeneration: 1
  operatorAudit:
    lastModifiedAt: "2026-10-03T11:35:37Z"
    lastModifiedBy: system:serviceaccount:kubernaut-system:remediationorchestrator-controller
    preRemediationSpecHash: sha256:885947ff9100a0e9292c6db1790245027c859d6cb76ecc51ccc343788f218880
  overallPhase: Completed
  phaseProgress:
    aiAnalysisRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: AIAnalysis
      name: ai-rr-825b58c1ca42-ffa5cb04
      namespace: kubernaut-system
    analyzingStartTime: "2026-10-03T11:35:38Z"
    effectivenessAssessmentRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: EffectivenessAssessment
      name: ea-rr-825b58c1ca42-ffa5cb04
      namespace: kubernaut-system
    executingStartTime: "2026-10-03T11:36:44Z"
    processingStartTime: "2026-10-03T11:35:37Z"
    signalProcessingRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: SignalProcessing
      name: sp-rr-825b58c1ca42-ffa5cb04
      namespace: kubernaut-system
    verificationDeadline: "2026-10-03T11:44:56Z"
    workflowExecutionRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: WorkflowExecution
      name: we-rr-825b58c1ca42-ffa5cb04
      namespace: kubernaut-system
  retentionExpiryTime: "2026-10-04T11:44:26Z"
  routingStatus:
    consecutiveFailureCount: 1
    nextAllowedExecution: "2026-10-03T11:45:30Z"
  startTime: "2026-10-03T11:35:37Z"
  timeoutConfig:
    analyzing: 10m0s
    executing: 30m0s
    global: 1h0m0s
    processing: 5m0s
  workflowSelection:
    confidence: "0.82"
    remediationTarget:
      apiVersion: apps/v1
      kind: Deployment
      name: batch-processor
      namespace: demo-scheduler
    selectedWorkflowRef:
      executionBundle: quay.io/kubernaut-cicd/test-workflows/remove-taint-job@sha256:2121ecf1001f6b95b7aeabda1fd4e2eb9eba9052a514a18a1e0f841d9958d561
      version: 1.6.3
      workflowId: 51247c9a-179f-54b8-b2fa-ece9fb80ef17
    signalTargetDisplay: Deployment/batch-processor
    targetDisplay: Deployment/batch-processor
    workflowDisplayName: RemoveTaint/remove-taint-v1
