apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxy
  namespace: demo-mesh-failure
spec:
  selector:
    matchLabels:
      app: istio-metrics
  namespaceSelector:
    matchNames:
      - demo-mesh-failure
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
