#!/usr/bin/env bash
SCENARIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_NAME="orphaned-pvc-no-action"
DEMO_NS="demo-orphaned-pvc"
ALERT_NAME="KubePersistentVolumeClaimOrphaned"
RESOURCE_TAPE="orphaned-pvc-no-action-pvcs.tape"
SCREENS_TAPE="orphaned-pvc-no-action-screens.tape"
APPROVAL_REQUIRED="false"
TERMINAL_STATE="ManualReviewRequired"
INJECT_CMD="bash ${SCENARIO_DIR}/inject-orphan-pvcs.sh"
SETUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh 2>/dev/null || true && kubectl apply -f ${SCENARIO_DIR}/manifests/ && sleep 5"
CLEANUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh"
source "$(cd "${SCENARIO_DIR}/../.." && pwd)/scripts/record-scenario.sh"
