apiVersion: kubernaut.ai/v1alpha1
kind: EffectivenessAssessment
metadata:
  creationTimestamp: "2026-10-02T18:26:14Z"
  generation: 1
  name: ea-rr-220b295e549b-0016b3e9
  namespace: kubernaut-system
  ownerReferences:
  - apiVersion: kubernaut.ai/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: RemediationRequest
    name: rr-220b295e549b-0016b3e9
    uid: 5e6c0b9a-5c1e-4b44-9f75-98f481ddb9be
  resourceVersion: "9402"
  uid: be5708e9-9c3c-405c-b35b-c7759fcbe086
spec:
  clusterID: remote-cluster
  config:
    stabilizationWindow: 5m0s
  correlationID: rr-220b295e549b-0016b3e9
  preRemediationSpecHash: sha256:e7953d1811b0b2b17b8cbe97ba57c71b66feb3329337efe72c9921ac266a1ee3
  remediationCreatedAt: "2026-10-02T18:13:30Z"
  remediationRequestPhase: Verifying
  remediationTarget:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-collector
    namespace: demo-monitoring
  signalName: RBACPolicyDenied
  signalTarget:
    kind: Deployment
    name: metrics-collector
    namespace: demo-monitoring
status:
  alertManagerCheckAfter: "2026-10-02T18:31:14Z"
  components: {}
  phase: Stabilizing
  prometheusCheckAfter: "2026-10-02T18:31:14Z"
  validityDeadline: "2026-10-02T18:33:14Z"
