apiVersion: kubernaut.ai/v1alpha1
kind: RemediationRequest
metadata:
  annotations:
    kubernaut.ai/created-at: "2026-10-02T18:13:30Z"
  creationTimestamp: "2026-10-02T18:13:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: remediation
    app.kubernetes.io/managed-by: gateway-service
  name: rr-220b295e549b-0016b3e9
  namespace: kubernaut-system
  resourceVersion: "9404"
  uid: 5e6c0b9a-5c1e-4b44-9f75-98f481ddb9be
spec:
  clusterID: remote-cluster
  firingTime: "2026-10-02T18:13:25Z"
  originalPayload: |
    {"receiver":"gateway-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"RBACPolicyDenied","cluster":"remote-cluster","container":"kube-state-metrics","deployment":"metrics-collector","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-monitoring","pod":"kube-state-metrics-78f5b5f8f9-msdfl","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"high"},"annotations":{"description":"Deployment metrics-collector in namespace demo-monitoring has zero available replicas. The pods are failing their readiness probes and workload availability is degraded.\n","summary":"Deployment metrics-collector in namespace demo-monitoring has zero available replicas despite spec.replicas \u003e 0.\n"},"startsAt":"2026-10-02T18:13:25.667Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus-fleet-spoke-0:9090/graph?g0.expr=kube_deployment_status_replicas_available%7Bdeployment%3D%22metrics-collector%22%2Cnamespace%3D%22demo-monitoring%22%7D+%3D%3D+0+and+kube_deployment_spec_replicas%7Bdeployment%3D%22metrics-collector%22%2Cnamespace%3D%22demo-monitoring%22%7D+%3E+0\u0026g0.tab=1","fingerprint":"a1e086e0cb067a14"}],"notification_reason":"first notification","groupLabels":{},"commonLabels":{"alertname":"RBACPolicyDenied","cluster":"remote-cluster","container":"kube-state-metrics","deployment":"metrics-collector","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-monitoring","pod":"kube-state-metrics-78f5b5f8f9-msdfl","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"high"},"commonAnnotations":{"description":"Deployment metrics-collector in namespace demo-monitoring has zero available replicas. The pods are failing their readiness probes and workload availability is degraded.\n","summary":"Deployment metrics-collector in namespace demo-monitoring has zero available replicas despite spec.replicas \u003e 0.\n"},"routeLabels":{},"externalURL":"http://alertmanager-7d8c7db59d-bknjw:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
  providerData: '{"labels":{"alertname":"RBACPolicyDenied","cluster":"remote-cluster","container":"kube-state-metrics","deployment":"metrics-collector","endpoint":"http-metrics","instance":"10.244.0.9:8080","job":"kube-state-metrics","namespace":"demo-monitoring","pod":"kube-state-metrics-78f5b5f8f9-msdfl","prometheus":"monitoring/fleet-spoke","service":"kube-state-metrics","severity":"high"},"namespace":"demo-monitoring"}'
  receivedTime: "2026-10-02T18:13:30Z"
  severity: high
  signalAnnotations:
    description: |
      Deployment metrics-collector in namespace demo-monitoring has zero available replicas. The pods are failing their readiness probes and workload availability is degraded.
    summary: |
      Deployment metrics-collector in namespace demo-monitoring has zero available replicas despite spec.replicas > 0.
  signalFingerprint: 220b295e549bbe945bea5107e0953ac89f85f4b7afa43d72b1dff67727353f05
  signalLabels:
    alertname: RBACPolicyDenied
    cluster: remote-cluster
    container: kube-state-metrics
    deployment: metrics-collector
    endpoint: http-metrics
    instance: 10.244.0.9:8080
    job: kube-state-metrics
    namespace: demo-monitoring
    pod: kube-state-metrics-78f5b5f8f9-msdfl
    prometheus: monitoring/fleet-spoke
    service: kube-state-metrics
    severity: high
  signalName: RBACPolicyDenied
  signalSource: prometheus
  signalType: alert
  targetResource:
    kind: Deployment
    name: metrics-collector
    namespace: demo-monitoring
  targetType: kubernetes
status:
  conditions:
  - lastTransitionTime: "2026-10-02T18:13:31Z"
    message: SignalProcessing CRD sp-rr-220b295e549b-0016b3e9 created successfully
    observedGeneration: 1
    reason: SignalProcessingCreated
    status: "True"
    type: SignalProcessingReady
  - lastTransitionTime: "2026-10-02T18:26:14Z"
    message: Remediation completed, verifying effectiveness
    observedGeneration: 1
    reason: Verifying
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-10-02T18:13:31Z"
    message: AIAnalysis CRD ai-rr-220b295e549b-0016b3e9 created successfully
    observedGeneration: 1
    reason: AIAnalysisCreated
    status: "True"
    type: AIAnalysisReady
  - lastTransitionTime: "2026-10-02T18:13:31Z"
    message: SignalProcessing completed successfully
    observedGeneration: 1
    reason: SignalProcessingSucceeded
    status: "True"
    type: SignalProcessingComplete
  - lastTransitionTime: "2026-10-02T18:14:37Z"
    message: AIAnalysis completed successfully
    observedGeneration: 1
    reason: AIAnalysisSucceeded
    status: "True"
    type: AIAnalysisComplete
  - lastTransitionTime: "2026-10-02T18:14:37Z"
    message: Pre-remediation hash captured
    observedGeneration: 1
    reason: HashCaptured
    status: "True"
    type: PreRemediationHashCaptured
  - lastTransitionTime: "2026-10-02T18:14:37Z"
    message: WorkflowExecution CRD we-rr-220b295e549b-0016b3e9 created successfully
    observedGeneration: 1
    reason: WorkflowExecutionCreated
    status: "True"
    type: WorkflowExecutionReady
  - lastTransitionTime: "2026-10-02T18:26:14Z"
    message: WorkflowExecution completed successfully
    observedGeneration: 1
    reason: WorkflowSucceeded
    status: "True"
    type: WorkflowExecutionComplete
  - lastTransitionTime: "2026-10-02T18:26:14Z"
    message: EffectivenessAssessment ea-rr-220b295e549b-0016b3e9 created, assessment
      in progress
    reason: AssessmentInProgress
    status: "False"
    type: EffectivenessAssessed
  deduplication:
    firstSeenAt: "2026-10-02T18:13:30Z"
    lastSeenAt: "2026-10-02T18:13:30Z"
    occurrenceCount: 1
  observedGeneration: 1
  operatorAudit:
    lastModifiedAt: "2026-10-02T18:13:31Z"
    lastModifiedBy: system:serviceaccount:kubernaut-system:remediationorchestrator-controller
    preRemediationSpecHash: sha256:e7953d1811b0b2b17b8cbe97ba57c71b66feb3329337efe72c9921ac266a1ee3
  overallPhase: Verifying
  phaseProgress:
    aiAnalysisRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: AIAnalysis
      name: ai-rr-220b295e549b-0016b3e9
      namespace: kubernaut-system
    analyzingStartTime: "2026-10-02T18:13:31Z"
    effectivenessAssessmentRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: EffectivenessAssessment
      name: ea-rr-220b295e549b-0016b3e9
      namespace: kubernaut-system
    executingStartTime: "2026-10-02T18:14:37Z"
    processingStartTime: "2026-10-02T18:13:31Z"
    signalProcessingRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: SignalProcessing
      name: sp-rr-220b295e549b-0016b3e9
      namespace: kubernaut-system
    verificationDeadline: "2026-10-02T18:33:44Z"
    workflowExecutionRef:
      apiVersion: kubernaut.ai/v1alpha1
      kind: WorkflowExecution
      name: we-rr-220b295e549b-0016b3e9
      namespace: kubernaut-system
  routingStatus: {}
  startTime: "2026-10-02T18:13:30Z"
  timeoutConfig:
    analyzing: 10m0s
    executing: 30m0s
    global: 1h0m0s
    processing: 5m0s
  workflowSelection:
    confidence: "0.90"
    remediationTarget:
      apiVersion: apps/v1
      kind: Deployment
      name: metrics-collector
      namespace: demo-monitoring
    selectedWorkflowRef:
      executionBundle: quay.io/kubernaut-cicd/test-workflows/restore-rolebinding-job@sha256:0691ef38a63b8647fa51894f49eba7b18dfea97e2b84d5371085649c291d5f8f
      version: 1.6.3
      workflowId: fb6a832d-510d-54a2-b512-cc2a52e31786
    signalTargetDisplay: Deployment/metrics-collector
    targetDisplay: Deployment/metrics-collector
    workflowDisplayName: RestoreRoleBinding/restore-rolebinding-v1
