apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-03T03:09:22Z"
    generateName: payment-service-7f7f779d-
    generation: 1
    labels:
      app: payment-service
      pod-template-hash: 7f7f779d
    name: payment-service-7f7f779d-cbx22
    namespace: demo-payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: payment-service-7f7f779d
      uid: 071cfe57-db5b-47c0-be8a-eb71a3277ea5
    resourceVersion: "59351"
    uid: 99f494c6-7539-4556-9ebc-a41251ed5df0
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: payment
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
        subPath: config.yaml
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-kf74r
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-worker-1790996710
    nodeSelector:
      kubernaut.ai/managed: "true"
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: payment-service-config
      name: config
    - name: kube-api-access-kf74r
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:09:23Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:09:22Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:09:31Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:09:31Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:09:22Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://174d98f6b3693eec447d4b85b973c0243d23a5ea22d9e47ba7b39b8ac527665f
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: payment
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-03T03:09:28Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-kf74r
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.17
    hostIPs:
    - ip: 10.89.0.17
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.2
    podIPs:
    - ip: 10.244.1.2
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-03T03:09:22Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-03T03:12:32Z"
    generateName: payment-service-7f7f779d-
    generation: 1
    labels:
      app: payment-service
      pod-template-hash: 7f7f779d
    name: payment-service-7f7f779d-px86s
    namespace: demo-payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: payment-service-7f7f779d
      uid: 071cfe57-db5b-47c0-be8a-eb71a3277ea5
    resourceVersion: "59832"
    uid: 02530fa2-de78-4222-8c41-3f853d727188
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: payment
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
        subPath: config.yaml
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ngs4x
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kubernaut-remote-cluster-worker-1790996710
    nodeSelector:
      kubernaut.ai/managed: "true"
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: payment-service-config
      name: config
    - name: kube-api-access-ngs4x
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    allocatedResources:
      cpu: 10m
      memory: 32Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:12:33Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:12:32Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:12:36Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:12:36Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:12:32Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 10m
        memory: 32Mi
      containerID: containerd://896807282d24f5ff93bc50803ffad0f5bcd6d71d20f226e5eca629616447bc0a
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imageID: quay.io/kubernaut-cicd/demo-http-server@sha256:bfb8c9879b679bd436e1a940864ad318c0bea0d9bb8fc14d35652cab49020b53
      lastState: {}
      name: payment
      ready: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-03T03:12:33Z"
      user:
        linux:
          gid: 65534
          supplementalGroups:
          - 65534
          uid: 65534
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ngs4x
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.89.0.17
    hostIPs:
    - ip: 10.89.0.17
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.4
    podIPs:
    - ip: 10.244.1.4
    qosClass: Burstable
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        memory: 32Mi
    startTime: "2026-10-03T03:12:32Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"payment-service","kubernaut.ai/managed":"true","kubernaut.ai/metrics":"true"},"name":"payment-service","namespace":"demo-payments"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"payment-service"},"type":"ClusterIP"}}
    creationTimestamp: "2026-10-03T03:09:22Z"
    labels:
      app: payment-service
      kubernaut.ai/managed: "true"
      kubernaut.ai/metrics: "true"
    name: payment-service
    namespace: demo-payments
    resourceVersion: "59268"
    uid: 60d9b082-52ff-4373-9495-2a09ecaa9347
  spec:
    clusterIP: 10.96.72.93
    clusterIPs:
    - 10.96.72.93
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: payment-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"payment-service","kubernaut.ai/managed":"true"},"name":"payment-service","namespace":"demo-payments"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"payment-service"}},"template":{"metadata":{"labels":{"app":"payment-service"}},"spec":{"containers":[{"env":[{"name":"CONFIG_PATH","value":"/etc/demo-http-server/config.yaml"}],"image":"quay.io/kubernaut-cicd/demo-http-server:1.0.0","livenessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":3,"periodSeconds":5},"name":"payment","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":2,"periodSeconds":3},"resources":{"limits":{"cpu":"50m","memory":"64Mi"},"requests":{"cpu":"10m","memory":"32Mi"}},"volumeMounts":[{"mountPath":"/etc/demo-http-server/config.yaml","name":"config","subPath":"config.yaml"}]}],"nodeSelector":{"kubernaut.ai/managed":"true"},"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/control-plane"}],"volumes":[{"configMap":{"name":"payment-service-config"},"name":"config"}]}}}}
    creationTimestamp: "2026-10-03T03:09:22Z"
    generation: 1
    labels:
      app: payment-service
      kubernaut.ai/managed: "true"
    name: payment-service
    namespace: demo-payments
    resourceVersion: "59833"
    uid: 33066bee-2781-46ce-9b04-5038e9e6d763
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: payment-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: payment-service
      spec:
        containers:
        - env:
          - name: CONFIG_PATH
            value: /etc/demo-http-server/config.yaml
          image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: payment
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/demo-http-server/config.yaml
            name: config
            subPath: config.yaml
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernaut.ai/managed: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        volumes:
        - configMap:
            defaultMode: 420
            name: payment-service-config
          name: config
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2026-10-03T03:09:22Z"
      lastUpdateTime: "2026-10-03T03:09:31Z"
      message: ReplicaSet "payment-service-7f7f779d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-10-03T03:12:37Z"
      lastUpdateTime: "2026-10-03T03:12:37Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    terminatingReplicas: 0
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-10-03T03:09:22Z"
    generation: 1
    labels:
      app: payment-service
      pod-template-hash: 7f7f779d
    name: payment-service-7f7f779d
    namespace: demo-payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: payment-service
      uid: 33066bee-2781-46ce-9b04-5038e9e6d763
    resourceVersion: "59831"
    uid: 071cfe57-db5b-47c0-be8a-eb71a3277ea5
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: payment-service
        pod-template-hash: 7f7f779d
    template:
      metadata:
        labels:
          app: payment-service
          pod-template-hash: 7f7f779d
      spec:
        containers:
        - env:
          - name: CONFIG_PATH
            value: /etc/demo-http-server/config.yaml
          image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: payment
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/demo-http-server/config.yaml
            name: config
            subPath: config.yaml
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernaut.ai/managed: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        volumes:
        - configMap:
            defaultMode: 420
            name: payment-service-config
          name: config
  status:
    availableReplicas: 2
    fullyLabeledReplicas: 2
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    terminatingReplicas: 0
kind: List
metadata:
  resourceVersion: ""
