apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-10-02T18:14:37Z"
  generateName: wfe-58b329b6cf3ac55b-
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 0404d230-ecc9-4306-a41a-4db60cae41bb
    batch.kubernetes.io/job-name: wfe-58b329b6cf3ac55b
    controller-uid: 0404d230-ecc9-4306-a41a-4db60cae41bb
    job-name: wfe-58b329b6cf3ac55b
    kubernaut.ai/execution-engine: job
    kubernaut.ai/workflow-execution: we-rr-220b295e549b-0016b3e9
  name: wfe-58b329b6cf3ac55b-h5tvn
  namespace: kubernaut-workflows
  resourceVersion: "5533"
  uid: 93810a6d-1796-462a-a70e-cea73db3fe60
spec:
  containers:
  - env:
    - name: TARGET_RESOURCE
      value: demo-monitoring/Deployment/metrics-collector
    - name: TARGET_RESOURCE_NAMESPACE
      value: demo-monitoring
    - name: TARGET_RESOURCE_KIND
      value: Deployment
    - name: TARGET_RESOURCE_NAME
      value: metrics-collector
    - name: HOME
      value: /tmp
    - name: TMPDIR
      value: /tmp
    image: quay.io/kubernaut-cicd/test-workflows/restore-rolebinding-job@sha256:0691ef38a63b8647fa51894f49eba7b18dfea97e2b84d5371085649c291d5f8f
    imagePullPolicy: IfNotPresent
    name: workflow
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ntpf8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kubernaut-remote-cluster-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: restore-rolebinding-v1-runner
  serviceAccountName: restore-rolebinding-v1-runner
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-ntpf8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-10-02T18:26:05Z"
    message: pod sandbox is not ready
    observedGeneration: 1
    reason: PodSandboxNotReady
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-10-02T18:14:37Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-10-02T18:26:04Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-10-02T18:26:04Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-10-02T18:14:37Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ae4c93340cb9f4116c6c5b020f5ac6332a96d663c1ac5beec020b5e28b75a625
    image: sha256:fafa5f027121fb8fb82c8116089f4bcd9f0e16344f4bf10d370dbc8221a2bb05
    imageID: quay.io/kubernaut-cicd/test-workflows/restore-rolebinding-job@sha256:0691ef38a63b8647fa51894f49eba7b18dfea97e2b84d5371085649c291d5f8f
    lastState: {}
    name: workflow
    ready: false
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://ae4c93340cb9f4116c6c5b020f5ac6332a96d663c1ac5beec020b5e28b75a625
        exitCode: 0
        finishedAt: "2026-10-02T18:26:03Z"
        reason: Completed
        startedAt: "2026-10-02T18:25:57Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 1001
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ntpf8
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.89.0.12
  hostIPs:
  - ip: 10.89.0.12
  observedGeneration: 1
  phase: Succeeded
  podIP: 10.244.0.18
  podIPs:
  - ip: 10.244.0.18
  qosClass: BestEffort
  resources: {}
  startTime: "2026-10-02T18:14:37Z"
