#!/usr/bin/env bash
SCENARIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_NAME="gitops-drift"
DEMO_NS="demo-gitops"
ALERT_NAME="KubePodCrashLooping"
RESOURCE_TAPE="gitops-drift-pods.tape"
SCREENS_TAPE="gitops-drift-screens.tape"
APPROVAL_REQUIRED="false"
TERMINAL_STATE="Completed"
INJECT_CMD="bash ${SCENARIO_DIR}/run.sh inject"
SETUP_CMD="bash ${SCENARIO_DIR}/run.sh setup"
CLEANUP_CMD="bash ${SCENARIO_DIR}/cleanup.sh"
source "$(cd "${SCENARIO_DIR}/../.." && pwd)/scripts/record-scenario.sh"
