apiVersion: v1
kind: Namespace
metadata:
  name: demo-controllers
  annotations:
    argocd.argoproj.io/instance: operator-oomkill-informer
  labels:
    kubernaut.ai/managed: "true"
    kubernaut.ai/environment: "production"
    kubernaut.ai/criticality: "high"
    kubernaut.ai/business-unit: "engineering"
