apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"release":"prometheus"},"name":"demo-app-alerts","namespace":"demo-scheduler"},"spec":{"groups":[{"name":"demo-app","rules":[{"alert":"KubePodNotScheduled","annotations":{"description":"One or more pods in namespace {{ $labels.namespace }} are in Pending state and have not been assigned to a node. Workload availability may be degraded.\n","summary":"Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been unscheduled for an extended period.\n"},"expr":"kube_pod_status_phase{namespace=\"demo-scheduler\", phase=\"Pending\"} == 1\n","for":"30s","labels":{"severity":"warning"}}]}]}}
      prometheus-operator-validated: "true"
    creationTimestamp: "2026-10-03T03:06:13Z"
    generation: 2
    labels:
      release: prometheus
    name: demo-app-alerts
    namespace: demo-scheduler
    resourceVersion: "58784"
    uid: 1774a33c-567b-42e7-88e1-3fab86544797
  spec:
    groups:
    - name: demo-app
      rules:
      - alert: KubePodNotScheduled
        annotations:
          description: |
            One or more pods in namespace {{ $labels.namespace }} are in Pending state and have not been assigned to a node. Workload availability may be degraded.
          summary: |
            Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been unscheduled for an extended period.
        expr: |
          kube_pod_status_phase{namespace="demo-scheduler", phase="Pending"} == 1
        for: 30s
        labels:
          cluster: remote-cluster
          severity: warning
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kubernaut-demo-scenarios","release":"kube-prometheus-stack"},"name":"demo-app-metrics","namespace":"demo-scheduler"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"http"}],"selector":{"matchLabels":{"kubernaut.ai/metrics":"true"}}}}
    creationTimestamp: "2026-10-03T03:06:13Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: kubernaut-demo-scenarios
      release: kube-prometheus-stack
    name: demo-app-metrics
    namespace: demo-scheduler
    resourceVersion: "58786"
    uid: 9137e298-edb3-4af3-97fe-6fd916c71eba
  spec:
    endpoints:
    - interval: 10s
      path: /metrics
      port: http
    selector:
      matchLabels:
        kubernaut.ai/metrics: "true"
kind: List
metadata:
  resourceVersion: ""
