apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-03T03:06:12Z"
    generateName: batch-processor-6547d9848-
    generation: 1
    labels:
      app: batch-processor
      pod-template-hash: 6547d9848
    name: batch-processor-6547d9848-wbxfp
    namespace: demo-scheduler
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: batch-processor-6547d9848
      uid: 8a94074a-f0f5-4342-b7db-8689020e23c2
    resourceVersion: "58781"
    uid: 6edd4a9d-bc57-44d3-9f58-905ffbfedb10
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: processor
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
        subPath: config.yaml
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-7j2nz
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeSelector:
      kubernaut.ai/workload-pool: "true"
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: batch-processor-config
      name: config
    - name: kube-api-access-7j2nz
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:06:12Z"
      message: '0/2 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector,
        1 node(s) had untolerated taint(s). preemption: 0/2 nodes are available: 2
        Preemption is not helpful for scheduling.'
      observedGeneration: 1
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-03T03:06:12Z"
    generateName: batch-processor-6547d9848-
    generation: 1
    labels:
      app: batch-processor
      pod-template-hash: 6547d9848
    name: batch-processor-6547d9848-xwgvd
    namespace: demo-scheduler
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: batch-processor-6547d9848
      uid: 8a94074a-f0f5-4342-b7db-8689020e23c2
    resourceVersion: "58778"
    uid: 4507b07e-6d3e-4bc4-b6f9-c876761b525e
  spec:
    containers:
    - env:
      - name: CONFIG_PATH
        value: /etc/demo-http-server/config.yaml
      image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: processor
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/demo-http-server/config.yaml
        name: config
        subPath: config.yaml
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-k84nl
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeSelector:
      kubernaut.ai/workload-pool: "true"
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: batch-processor-config
      name: config
    - name: kube-api-access-k84nl
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T03:06:12Z"
      message: '0/2 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector,
        1 node(s) had untolerated taint(s). preemption: 0/2 nodes are available: 2
        Preemption is not helpful for scheduling.'
      observedGeneration: 1
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"batch-processor","kubernaut.ai/managed":"true","kubernaut.ai/metrics":"true"},"name":"batch-processor","namespace":"demo-scheduler"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"batch-processor"},"type":"ClusterIP"}}
    creationTimestamp: "2026-10-03T03:06:12Z"
    labels:
      app: batch-processor
      kubernaut.ai/managed: "true"
      kubernaut.ai/metrics: "true"
    name: batch-processor
    namespace: demo-scheduler
    resourceVersion: "58763"
    uid: 2d684ff8-955b-4563-bf3a-4a82d72bb706
  spec:
    clusterIP: 10.96.76.182
    clusterIPs:
    - 10.96.76.182
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: batch-processor
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"batch-processor","kubernaut.ai/managed":"true"},"name":"batch-processor","namespace":"demo-scheduler"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"batch-processor"}},"template":{"metadata":{"labels":{"app":"batch-processor"}},"spec":{"containers":[{"env":[{"name":"CONFIG_PATH","value":"/etc/demo-http-server/config.yaml"}],"image":"quay.io/kubernaut-cicd/demo-http-server:1.0.0","livenessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":3,"periodSeconds":5},"name":"processor","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":2,"periodSeconds":3},"resources":{"limits":{"cpu":"50m","memory":"64Mi"},"requests":{"cpu":"10m","memory":"32Mi"}},"volumeMounts":[{"mountPath":"/etc/demo-http-server/config.yaml","name":"config","subPath":"config.yaml"}]}],"nodeSelector":{"kubernaut.ai/workload-pool":"true"},"volumes":[{"configMap":{"name":"batch-processor-config"},"name":"config"}]}}}}
    creationTimestamp: "2026-10-03T03:06:12Z"
    generation: 1
    labels:
      app: batch-processor
      kubernaut.ai/managed: "true"
    name: batch-processor
    namespace: demo-scheduler
    resourceVersion: "58779"
    uid: 5150db3f-7838-4967-a90d-c5b3c745334a
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: batch-processor
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: batch-processor
      spec:
        containers:
        - env:
          - name: CONFIG_PATH
            value: /etc/demo-http-server/config.yaml
          image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: processor
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/demo-http-server/config.yaml
            name: config
            subPath: config.yaml
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernaut.ai/workload-pool: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: batch-processor-config
          name: config
  status:
    conditions:
    - lastTransitionTime: "2026-10-03T03:06:12Z"
      lastUpdateTime: "2026-10-03T03:06:12Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2026-10-03T03:06:12Z"
      lastUpdateTime: "2026-10-03T03:06:12Z"
      message: ReplicaSet "batch-processor-6547d9848" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 2
    terminatingReplicas: 0
    unavailableReplicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-10-03T03:06:12Z"
    generation: 1
    labels:
      app: batch-processor
      pod-template-hash: 6547d9848
    name: batch-processor-6547d9848
    namespace: demo-scheduler
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: batch-processor
      uid: 5150db3f-7838-4967-a90d-c5b3c745334a
    resourceVersion: "58777"
    uid: 8a94074a-f0f5-4342-b7db-8689020e23c2
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: batch-processor
        pod-template-hash: 6547d9848
    template:
      metadata:
        labels:
          app: batch-processor
          pod-template-hash: 6547d9848
      spec:
        containers:
        - env:
          - name: CONFIG_PATH
            value: /etc/demo-http-server/config.yaml
          image: quay.io/kubernaut-cicd/demo-http-server:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: processor
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/demo-http-server/config.yaml
            name: config
            subPath: config.yaml
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernaut.ai/workload-pool: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: batch-processor-config
          name: config
  status:
    fullyLabeledReplicas: 2
    observedGeneration: 1
    replicas: 2
    terminatingReplicas: 0
kind: List
metadata:
  resourceVersion: ""
